// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/stream/stream.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"` // 可选指定分辨率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlReq) Reset() {
	*x = GetPlayUrlReq{}
	mi := &file_rpc_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlReq) ProtoMessage() {}

func (x *GetPlayUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlReq.ProtoReflect.Descriptor instead.
func (*GetPlayUrlReq) Descriptor() ([]byte, []int) {
	return file_rpc_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayUrlReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetPlayUrlReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPlayUrlReq) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type GetPlayUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M3U8Url       string                 `protobuf:"bytes,1,opt,name=m3u8_url,json=m3u8Url,proto3" json:"m3u8_url,omitempty"`
	Streams       []*PlayStream          `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlResp) Reset() {
	*x = GetPlayUrlResp{}
	mi := &file_rpc_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlResp) ProtoMessage() {}

func (x *GetPlayUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlResp.ProtoReflect.Descriptor instead.
func (*GetPlayUrlResp) Descriptor() ([]byte, []int) {
	return file_rpc_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayUrlResp) GetM3U8Url() string {
	if x != nil {
		return x.M3U8Url
	}
	return ""
}

func (x *GetPlayUrlResp) GetStreams() []*PlayStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

type PlayStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayStream) Reset() {
	*x = PlayStream{}
	mi := &file_rpc_stream_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayStream) ProtoMessage() {}

func (x *PlayStream) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_stream_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStream.ProtoReflect.Descriptor instead.
func (*PlayStream) Descriptor() ([]byte, []int) {
	return file_rpc_stream_stream_proto_rawDescGZIP(), []int{2}
}

func (x *PlayStream) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *PlayStream) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PlayStream) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type IncrPlayCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrPlayCountReq) Reset() {
	*x = IncrPlayCountReq{}
	mi := &file_rpc_stream_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrPlayCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrPlayCountReq) ProtoMessage() {}

func (x *IncrPlayCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_stream_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrPlayCountReq.ProtoReflect.Descriptor instead.
func (*IncrPlayCountReq) Descriptor() ([]byte, []int) {
	return file_rpc_stream_stream_proto_rawDescGZIP(), []int{3}
}

func (x *IncrPlayCountReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type IncrPlayCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayCount     int64                  `protobuf:"varint,1,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrPlayCountResp) Reset() {
	*x = IncrPlayCountResp{}
	mi := &file_rpc_stream_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrPlayCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrPlayCountResp) ProtoMessage() {}

func (x *IncrPlayCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_stream_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrPlayCountResp.ProtoReflect.Descriptor instead.
func (*IncrPlayCountResp) Descriptor() ([]byte, []int) {
	return file_rpc_stream_stream_proto_rawDescGZIP(), []int{4}
}

func (x *IncrPlayCountResp) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

var File_rpc_stream_stream_proto protoreflect.FileDescriptor

const file_rpc_stream_stream_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/stream/stream.proto\x12\x06stream\"c\n" +
	"\rGetPlayUrlReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\"Y\n" +
	"\x0eGetPlayUrlResp\x12\x19\n" +
	"\bm3u8_url\x18\x01 \x01(\tR\am3u8Url\x12,\n" +
	"\astreams\x18\x02 \x03(\v2\x12.stream.PlayStreamR\astreams\"X\n" +
	"\n" +
	"PlayStream\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\"-\n" +
	"\x10IncrPlayCountReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"2\n" +
	"\x11IncrPlayCountResp\x12\x1d\n" +
	"\n" +
	"play_count\x18\x01 \x01(\x03R\tplayCount2\x8b\x01\n" +
	"\x06Stream\x12;\n" +
	"\n" +
	"GetPlayUrl\x12\x15.stream.GetPlayUrlReq\x1a\x16.stream.GetPlayUrlResp\x12D\n" +
	"\rIncrPlayCount\x12\x18.stream.IncrPlayCountReq\x1a\x19.stream.IncrPlayCountRespB\n" +
	"Z\b./streamb\x06proto3"

var (
	file_rpc_stream_stream_proto_rawDescOnce sync.Once
	file_rpc_stream_stream_proto_rawDescData []byte
)

func file_rpc_stream_stream_proto_rawDescGZIP() []byte {
	file_rpc_stream_stream_proto_rawDescOnce.Do(func() {
		file_rpc_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_stream_stream_proto_rawDesc), len(file_rpc_stream_stream_proto_rawDesc)))
	})
	return file_rpc_stream_stream_proto_rawDescData
}

var file_rpc_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_stream_stream_proto_goTypes = []any{
	(*GetPlayUrlReq)(nil),     // 0: stream.GetPlayUrlReq
	(*GetPlayUrlResp)(nil),    // 1: stream.GetPlayUrlResp
	(*PlayStream)(nil),        // 2: stream.PlayStream
	(*IncrPlayCountReq)(nil),  // 3: stream.IncrPlayCountReq
	(*IncrPlayCountResp)(nil), // 4: stream.IncrPlayCountResp
}
var file_rpc_stream_stream_proto_depIdxs = []int32{
	2, // 0: stream.GetPlayUrlResp.streams:type_name -> stream.PlayStream
	0, // 1: stream.Stream.GetPlayUrl:input_type -> stream.GetPlayUrlReq
	3, // 2: stream.Stream.IncrPlayCount:input_type -> stream.IncrPlayCountReq
	1, // 3: stream.Stream.GetPlayUrl:output_type -> stream.GetPlayUrlResp
	4, // 4: stream.Stream.IncrPlayCount:output_type -> stream.IncrPlayCountResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_stream_stream_proto_init() }
func file_rpc_stream_stream_proto_init() {
	if File_rpc_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_stream_stream_proto_rawDesc), len(file_rpc_stream_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_stream_stream_proto_goTypes,
		DependencyIndexes: file_rpc_stream_stream_proto_depIdxs,
		MessageInfos:      file_rpc_stream_stream_proto_msgTypes,
	}.Build()
	File_rpc_stream_stream_proto = out.File
	file_rpc_stream_stream_proto_goTypes = nil
	file_rpc_stream_stream_proto_depIdxs = nil
}
