// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	mi := &file_rpc_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResp) Reset() {
	*x = AdminLoginResp{}
	mi := &file_rpc_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResp) ProtoMessage() {}

func (x *AdminLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResp.ProtoReflect.Descriptor instead.
func (*AdminLoginResp) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminLoginResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AdminListVideosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // -1 表示全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListVideosReq) Reset() {
	*x = AdminListVideosReq{}
	mi := &file_rpc_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListVideosReq) ProtoMessage() {}

func (x *AdminListVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListVideosReq.ProtoReflect.Descriptor instead.
func (*AdminListVideosReq) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminListVideosReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AdminListVideosReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminListVideosReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminVideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	PlayCount     int64                  `protobuf:"varint,7,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminVideoInfo) Reset() {
	*x = AdminVideoInfo{}
	mi := &file_rpc_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminVideoInfo) ProtoMessage() {}

func (x *AdminVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminVideoInfo.ProtoReflect.Descriptor instead.
func (*AdminVideoInfo) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminVideoInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminVideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *AdminVideoInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminVideoInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminVideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminVideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *AdminVideoInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AdminListVideosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*AdminVideoInfo      `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListVideosResp) Reset() {
	*x = AdminListVideosResp{}
	mi := &file_rpc_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListVideosResp) ProtoMessage() {}

func (x *AdminListVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListVideosResp.ProtoReflect.Descriptor instead.
func (*AdminListVideosResp) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminListVideosResp) GetVideos() []*AdminVideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *AdminListVideosResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *AdminListVideosResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ApproveVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveVideoReq) Reset() {
	*x = ApproveVideoReq{}
	mi := &file_rpc_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveVideoReq) ProtoMessage() {}

func (x *ApproveVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveVideoReq.ProtoReflect.Descriptor instead.
func (*ApproveVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ApproveVideoReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type ApproveVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveVideoResp) Reset() {
	*x = ApproveVideoResp{}
	mi := &file_rpc_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveVideoResp) ProtoMessage() {}

func (x *ApproveVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveVideoResp.ProtoReflect.Descriptor instead.
func (*ApproveVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{6}
}

type RejectVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectVideoReq) Reset() {
	*x = RejectVideoReq{}
	mi := &file_rpc_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectVideoReq) ProtoMessage() {}

func (x *RejectVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectVideoReq.ProtoReflect.Descriptor instead.
func (*RejectVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RejectVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *RejectVideoReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type RejectVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectVideoResp) Reset() {
	*x = RejectVideoResp{}
	mi := &file_rpc_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectVideoResp) ProtoMessage() {}

func (x *RejectVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectVideoResp.ProtoReflect.Descriptor instead.
func (*RejectVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{8}
}

type AdminDeleteVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteVideoReq) Reset() {
	*x = AdminDeleteVideoReq{}
	mi := &file_rpc_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteVideoReq) ProtoMessage() {}

func (x *AdminDeleteVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteVideoReq.ProtoReflect.Descriptor instead.
func (*AdminDeleteVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminDeleteVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *AdminDeleteVideoReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type AdminDeleteVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteVideoResp) Reset() {
	*x = AdminDeleteVideoResp{}
	mi := &file_rpc_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteVideoResp) ProtoMessage() {}

func (x *AdminDeleteVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteVideoResp.ProtoReflect.Descriptor instead.
func (*AdminDeleteVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_admin_admin_proto_rawDescGZIP(), []int{10}
}

var File_rpc_admin_admin_proto protoreflect.FileDescriptor

const file_rpc_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/admin/admin.proto\x12\x05admin\"G\n" +
	"\rAdminLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x0eAdminLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"Z\n" +
	"\x12AdminListVideosReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xde\x01\n" +
	"\x0eAdminVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"play_count\x18\a \x01(\x03R\tplayCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\x80\x01\n" +
	"\x13AdminListVideosResp\x12-\n" +
	"\x06videos\x18\x01 \x03(\v2\x15.admin.AdminVideoInfoR\x06videos\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"G\n" +
	"\x0fApproveVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"\x12\n" +
	"\x10ApproveVideoResp\"F\n" +
	"\x0eRejectVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"\x11\n" +
	"\x0fRejectVideoResp\"K\n" +
	"\x13AdminDeleteVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"\x16\n" +
	"\x14AdminDeleteVideoResp2\xce\x02\n" +
	"\x05Admin\x129\n" +
	"\n" +
	"AdminLogin\x12\x14.admin.AdminLoginReq\x1a\x15.admin.AdminLoginResp\x12C\n" +
	"\n" +
	"ListVideos\x12\x19.admin.AdminListVideosReq\x1a\x1a.admin.AdminListVideosResp\x12?\n" +
	"\fApproveVideo\x12\x16.admin.ApproveVideoReq\x1a\x17.admin.ApproveVideoResp\x12<\n" +
	"\vRejectVideo\x12\x15.admin.RejectVideoReq\x1a\x16.admin.RejectVideoResp\x12F\n" +
	"\vDeleteVideo\x12\x1a.admin.AdminDeleteVideoReq\x1a\x1b.admin.AdminDeleteVideoRespB\tZ\a./adminb\x06proto3"

var (
	file_rpc_admin_admin_proto_rawDescOnce sync.Once
	file_rpc_admin_admin_proto_rawDescData []byte
)

func file_rpc_admin_admin_proto_rawDescGZIP() []byte {
	file_rpc_admin_admin_proto_rawDescOnce.Do(func() {
		file_rpc_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_admin_admin_proto_rawDesc), len(file_rpc_admin_admin_proto_rawDesc)))
	})
	return file_rpc_admin_admin_proto_rawDescData
}

var file_rpc_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_admin_admin_proto_goTypes = []any{
	(*AdminLoginReq)(nil),        // 0: admin.AdminLoginReq
	(*AdminLoginResp)(nil),       // 1: admin.AdminLoginResp
	(*AdminListVideosReq)(nil),   // 2: admin.AdminListVideosReq
	(*AdminVideoInfo)(nil),       // 3: admin.AdminVideoInfo
	(*AdminListVideosResp)(nil),  // 4: admin.AdminListVideosResp
	(*ApproveVideoReq)(nil),      // 5: admin.ApproveVideoReq
	(*ApproveVideoResp)(nil),     // 6: admin.ApproveVideoResp
	(*RejectVideoReq)(nil),       // 7: admin.RejectVideoReq
	(*RejectVideoResp)(nil),      // 8: admin.RejectVideoResp
	(*AdminDeleteVideoReq)(nil),  // 9: admin.AdminDeleteVideoReq
	(*AdminDeleteVideoResp)(nil), // 10: admin.AdminDeleteVideoResp
}
var file_rpc_admin_admin_proto_depIdxs = []int32{
	3,  // 0: admin.AdminListVideosResp.videos:type_name -> admin.AdminVideoInfo
	0,  // 1: admin.Admin.AdminLogin:input_type -> admin.AdminLoginReq
	2,  // 2: admin.Admin.ListVideos:input_type -> admin.AdminListVideosReq
	5,  // 3: admin.Admin.ApproveVideo:input_type -> admin.ApproveVideoReq
	7,  // 4: admin.Admin.RejectVideo:input_type -> admin.RejectVideoReq
	9,  // 5: admin.Admin.DeleteVideo:input_type -> admin.AdminDeleteVideoReq
	1,  // 6: admin.Admin.AdminLogin:output_type -> admin.AdminLoginResp
	4,  // 7: admin.Admin.ListVideos:output_type -> admin.AdminListVideosResp
	6,  // 8: admin.Admin.ApproveVideo:output_type -> admin.ApproveVideoResp
	8,  // 9: admin.Admin.RejectVideo:output_type -> admin.RejectVideoResp
	10, // 10: admin.Admin.DeleteVideo:output_type -> admin.AdminDeleteVideoResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_admin_admin_proto_init() }
func file_rpc_admin_admin_proto_init() {
	if File_rpc_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_admin_admin_proto_rawDesc), len(file_rpc_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_admin_admin_proto_goTypes,
		DependencyIndexes: file_rpc_admin_admin_proto_depIdxs,
		MessageInfos:      file_rpc_admin_admin_proto_msgTypes,
	}.Build()
	File_rpc_admin_admin_proto = out.File
	file_rpc_admin_admin_proto_goTypes = nil
	file_rpc_admin_admin_proto_depIdxs = nil
}
