// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: rpc/admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_AdminLogin_FullMethodName   = "/admin.Admin/AdminLogin"
	Admin_ListVideos_FullMethodName   = "/admin.Admin/ListVideos"
	Admin_ApproveVideo_FullMethodName = "/admin.Admin/ApproveVideo"
	Admin_RejectVideo_FullMethodName  = "/admin.Admin/RejectVideo"
	Admin_DeleteVideo_FullMethodName  = "/admin.Admin/DeleteVideo"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error)
	ListVideos(ctx context.Context, in *AdminListVideosReq, opts ...grpc.CallOption) (*AdminListVideosResp, error)
	ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*ApproveVideoResp, error)
	RejectVideo(ctx context.Context, in *RejectVideoReq, opts ...grpc.CallOption) (*RejectVideoResp, error)
	DeleteVideo(ctx context.Context, in *AdminDeleteVideoReq, opts ...grpc.CallOption) (*AdminDeleteVideoResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLoginResp)
	err := c.cc.Invoke(ctx, Admin_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListVideos(ctx context.Context, in *AdminListVideosReq, opts ...grpc.CallOption) (*AdminListVideosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListVideosResp)
	err := c.cc.Invoke(ctx, Admin_ListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*ApproveVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveVideoResp)
	err := c.cc.Invoke(ctx, Admin_ApproveVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RejectVideo(ctx context.Context, in *RejectVideoReq, opts ...grpc.CallOption) (*RejectVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectVideoResp)
	err := c.cc.Invoke(ctx, Admin_RejectVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteVideo(ctx context.Context, in *AdminDeleteVideoReq, opts ...grpc.CallOption) (*AdminDeleteVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteVideoResp)
	err := c.cc.Invoke(ctx, Admin_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error)
	ListVideos(context.Context, *AdminListVideosReq) (*AdminListVideosResp, error)
	ApproveVideo(context.Context, *ApproveVideoReq) (*ApproveVideoResp, error)
	RejectVideo(context.Context, *RejectVideoReq) (*RejectVideoResp, error)
	DeleteVideo(context.Context, *AdminDeleteVideoReq) (*AdminDeleteVideoResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAdminServer) ListVideos(context.Context, *AdminListVideosReq) (*AdminListVideosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVideos not implemented")
}
func (UnimplementedAdminServer) ApproveVideo(context.Context, *ApproveVideoReq) (*ApproveVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveVideo not implemented")
}
func (UnimplementedAdminServer) RejectVideo(context.Context, *RejectVideoReq) (*RejectVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectVideo not implemented")
}
func (UnimplementedAdminServer) DeleteVideo(context.Context, *AdminDeleteVideoReq) (*AdminDeleteVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListVideos(ctx, req.(*AdminListVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ApproveVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ApproveVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ApproveVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ApproveVideo(ctx, req.(*ApproveVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RejectVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RejectVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RejectVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RejectVideo(ctx, req.(*RejectVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteVideo(ctx, req.(*AdminDeleteVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _Admin_AdminLogin_Handler,
		},
		{
			MethodName: "ListVideos",
			Handler:    _Admin_ListVideos_Handler,
		},
		{
			MethodName: "ApproveVideo",
			Handler:    _Admin_ApproveVideo_Handler,
		},
		{
			MethodName: "RejectVideo",
			Handler:    _Admin_RejectVideo_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _Admin_DeleteVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/admin/admin.proto",
}
