// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package searchclient

import (
	"context"

	"gopan/rpc/search/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IndexVideoReq    = search.IndexVideoReq
	IndexVideoResp   = search.IndexVideoResp
	RemoveVideoReq   = search.RemoveVideoReq
	RemoveVideoResp  = search.RemoveVideoResp
	SearchVideoInfo  = search.SearchVideoInfo
	SearchVideosReq  = search.SearchVideosReq
	SearchVideosResp = search.SearchVideosResp

	Search interface {
		// 搜索视频
		SearchVideos(ctx context.Context, in *SearchVideosReq, opts ...grpc.CallOption) (*SearchVideosResp, error)
		// 索引视频(创建/更新)
		IndexVideo(ctx context.Context, in *IndexVideoReq, opts ...grpc.CallOption) (*IndexVideoResp, error)
		// 从索引中移除
		RemoveVideo(ctx context.Context, in *RemoveVideoReq, opts ...grpc.CallOption) (*RemoveVideoResp, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

// 搜索视频
func (m *defaultSearch) SearchVideos(ctx context.Context, in *SearchVideosReq, opts ...grpc.CallOption) (*SearchVideosResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.SearchVideos(ctx, in, opts...)
}

// 索引视频(创建/更新)
func (m *defaultSearch) IndexVideo(ctx context.Context, in *IndexVideoReq, opts ...grpc.CallOption) (*IndexVideoResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.IndexVideo(ctx, in, opts...)
}

// 从索引中移除
func (m *defaultSearch) RemoveVideo(ctx context.Context, in *RemoveVideoReq, opts ...grpc.CallOption) (*RemoveVideoResp, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.RemoveVideo(ctx, in, opts...)
}
