// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: transcode.proto

package transcodeclient

import (
	"context"

	"gopan/rpc/transcode/transcode"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	QueryTaskReq    = transcode.QueryTaskReq
	QueryTaskResp   = transcode.QueryTaskResp
	SubmitTaskReq   = transcode.SubmitTaskReq
	SubmitTaskResp  = transcode.SubmitTaskResp
	TranscodeResult = transcode.TranscodeResult

	Transcode interface {
		// 提交转码任务
		SubmitTask(ctx context.Context, in *SubmitTaskReq, opts ...grpc.CallOption) (*SubmitTaskResp, error)
		// 查询转码状态
		QueryTask(ctx context.Context, in *QueryTaskReq, opts ...grpc.CallOption) (*QueryTaskResp, error)
	}

	defaultTranscode struct {
		cli zrpc.Client
	}
)

func NewTranscode(cli zrpc.Client) Transcode {
	return &defaultTranscode{
		cli: cli,
	}
}

// 提交转码任务
func (m *defaultTranscode) SubmitTask(ctx context.Context, in *SubmitTaskReq, opts ...grpc.CallOption) (*SubmitTaskResp, error) {
	client := transcode.NewTranscodeClient(m.cli.Conn())
	return client.SubmitTask(ctx, in, opts...)
}

// 查询转码状态
func (m *defaultTranscode) QueryTask(ctx context.Context, in *QueryTaskReq, opts ...grpc.CallOption) (*QueryTaskResp, error) {
	client := transcode.NewTranscodeClient(m.cli.Conn())
	return client.QueryTask(ctx, in, opts...)
}
