// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stream.proto

package server

import (
	"context"

	"gopan/rpc/stream/internal/logic"
	"gopan/rpc/stream/internal/svc"
	"gopan/rpc/stream/stream"
)

type StreamServer struct {
	svcCtx *svc.ServiceContext
	stream.UnimplementedStreamServer
}

func NewStreamServer(svcCtx *svc.ServiceContext) *StreamServer {
	return &StreamServer{
		svcCtx: svcCtx,
	}
}

// 获取播放地址(带防盗链签名)
func (s *StreamServer) GetPlayUrl(ctx context.Context, in *stream.GetPlayUrlReq) (*stream.GetPlayUrlResp, error) {
	l := logic.NewGetPlayUrlLogic(ctx, s.svcCtx)
	return l.GetPlayUrl(in)
}

// 增加播放计数
func (s *StreamServer) IncrPlayCount(ctx context.Context, in *stream.IncrPlayCountReq) (*stream.IncrPlayCountResp, error) {
	l := logic.NewIncrPlayCountLogic(ctx, s.svcCtx)
	return l.IncrPlayCount(in)
}
