// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: rpc/interact/interact.proto

package interact

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interact_Like_FullMethodName              = "/interact.Interact/Like"
	Interact_Unlike_FullMethodName            = "/interact.Interact/Unlike"
	Interact_GetLikeStatus_FullMethodName     = "/interact.Interact/GetLikeStatus"
	Interact_Favorite_FullMethodName          = "/interact.Interact/Favorite"
	Interact_Unfavorite_FullMethodName        = "/interact.Interact/Unfavorite"
	Interact_GetFavoriteStatus_FullMethodName = "/interact.Interact/GetFavoriteStatus"
	Interact_PostComment_FullMethodName       = "/interact.Interact/PostComment"
	Interact_ListComments_FullMethodName      = "/interact.Interact/ListComments"
	Interact_DeleteComment_FullMethodName     = "/interact.Interact/DeleteComment"
	Interact_SendDanmaku_FullMethodName       = "/interact.Interact/SendDanmaku"
	Interact_GetDanmakus_FullMethodName       = "/interact.Interact/GetDanmakus"
)

// InteractClient is the client API for Interact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 互动服务
type InteractClient interface {
	// 点赞
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
	// 取消点赞
	Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error)
	// 获取点赞状态
	GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error)
	// 收藏
	Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error)
	// 取消收藏
	Unfavorite(ctx context.Context, in *UnfavoriteReq, opts ...grpc.CallOption) (*UnfavoriteResp, error)
	// 获取收藏状态
	GetFavoriteStatus(ctx context.Context, in *GetFavoriteStatusReq, opts ...grpc.CallOption) (*GetFavoriteStatusResp, error)
	// 发送评论
	PostComment(ctx context.Context, in *PostCommentReq, opts ...grpc.CallOption) (*PostCommentResp, error)
	// 获取评论列表
	ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
	// 删除评论
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	// 发送弹幕
	SendDanmaku(ctx context.Context, in *SendDanmakuReq, opts ...grpc.CallOption) (*SendDanmakuResp, error)
	// 获取弹幕列表
	GetDanmakus(ctx context.Context, in *GetDanmakusReq, opts ...grpc.CallOption) (*GetDanmakusResp, error)
}

type interactClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractClient(cc grpc.ClientConnInterface) InteractClient {
	return &interactClient{cc}
}

func (c *interactClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeResp)
	err := c.cc.Invoke(ctx, Interact_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeResp)
	err := c.cc.Invoke(ctx, Interact_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikeStatusResp)
	err := c.cc.Invoke(ctx, Interact_GetLikeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteResp)
	err := c.cc.Invoke(ctx, Interact_Favorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) Unfavorite(ctx context.Context, in *UnfavoriteReq, opts ...grpc.CallOption) (*UnfavoriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfavoriteResp)
	err := c.cc.Invoke(ctx, Interact_Unfavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) GetFavoriteStatus(ctx context.Context, in *GetFavoriteStatusReq, opts ...grpc.CallOption) (*GetFavoriteStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteStatusResp)
	err := c.cc.Invoke(ctx, Interact_GetFavoriteStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) PostComment(ctx context.Context, in *PostCommentReq, opts ...grpc.CallOption) (*PostCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCommentResp)
	err := c.cc.Invoke(ctx, Interact_PostComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResp)
	err := c.cc.Invoke(ctx, Interact_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, Interact_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) SendDanmaku(ctx context.Context, in *SendDanmakuReq, opts ...grpc.CallOption) (*SendDanmakuResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDanmakuResp)
	err := c.cc.Invoke(ctx, Interact_SendDanmaku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactClient) GetDanmakus(ctx context.Context, in *GetDanmakusReq, opts ...grpc.CallOption) (*GetDanmakusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDanmakusResp)
	err := c.cc.Invoke(ctx, Interact_GetDanmakus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractServer is the server API for Interact service.
// All implementations must embed UnimplementedInteractServer
// for forward compatibility.
//
// 互动服务
type InteractServer interface {
	// 点赞
	Like(context.Context, *LikeReq) (*LikeResp, error)
	// 取消点赞
	Unlike(context.Context, *UnlikeReq) (*UnlikeResp, error)
	// 获取点赞状态
	GetLikeStatus(context.Context, *GetLikeStatusReq) (*GetLikeStatusResp, error)
	// 收藏
	Favorite(context.Context, *FavoriteReq) (*FavoriteResp, error)
	// 取消收藏
	Unfavorite(context.Context, *UnfavoriteReq) (*UnfavoriteResp, error)
	// 获取收藏状态
	GetFavoriteStatus(context.Context, *GetFavoriteStatusReq) (*GetFavoriteStatusResp, error)
	// 发送评论
	PostComment(context.Context, *PostCommentReq) (*PostCommentResp, error)
	// 获取评论列表
	ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error)
	// 删除评论
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	// 发送弹幕
	SendDanmaku(context.Context, *SendDanmakuReq) (*SendDanmakuResp, error)
	// 获取弹幕列表
	GetDanmakus(context.Context, *GetDanmakusReq) (*GetDanmakusResp, error)
	mustEmbedUnimplementedInteractServer()
}

// UnimplementedInteractServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractServer struct{}

func (UnimplementedInteractServer) Like(context.Context, *LikeReq) (*LikeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedInteractServer) Unlike(context.Context, *UnlikeReq) (*UnlikeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedInteractServer) GetLikeStatus(context.Context, *GetLikeStatusReq) (*GetLikeStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikeStatus not implemented")
}
func (UnimplementedInteractServer) Favorite(context.Context, *FavoriteReq) (*FavoriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Favorite not implemented")
}
func (UnimplementedInteractServer) Unfavorite(context.Context, *UnfavoriteReq) (*UnfavoriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unfavorite not implemented")
}
func (UnimplementedInteractServer) GetFavoriteStatus(context.Context, *GetFavoriteStatusReq) (*GetFavoriteStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteStatus not implemented")
}
func (UnimplementedInteractServer) PostComment(context.Context, *PostCommentReq) (*PostCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostComment not implemented")
}
func (UnimplementedInteractServer) ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedInteractServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedInteractServer) SendDanmaku(context.Context, *SendDanmakuReq) (*SendDanmakuResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDanmaku not implemented")
}
func (UnimplementedInteractServer) GetDanmakus(context.Context, *GetDanmakusReq) (*GetDanmakusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDanmakus not implemented")
}
func (UnimplementedInteractServer) mustEmbedUnimplementedInteractServer() {}
func (UnimplementedInteractServer) testEmbeddedByValue()                  {}

// UnsafeInteractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractServer will
// result in compilation errors.
type UnsafeInteractServer interface {
	mustEmbedUnimplementedInteractServer()
}

func RegisterInteractServer(s grpc.ServiceRegistrar, srv InteractServer) {
	// If the following call panics, it indicates UnimplementedInteractServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interact_ServiceDesc, srv)
}

func _Interact_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).Unlike(ctx, req.(*UnlikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_GetLikeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikeStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).GetLikeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_GetLikeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).GetLikeStatus(ctx, req.(*GetLikeStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_Favorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).Favorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_Favorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).Favorite(ctx, req.(*FavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_Unfavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).Unfavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_Unfavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).Unfavorite(ctx, req.(*UnfavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_GetFavoriteStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).GetFavoriteStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_GetFavoriteStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).GetFavoriteStatus(ctx, req.(*GetFavoriteStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_PostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).PostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_PostComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).PostComment(ctx, req.(*PostCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).ListComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_SendDanmaku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDanmakuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).SendDanmaku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_SendDanmaku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).SendDanmaku(ctx, req.(*SendDanmakuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interact_GetDanmakus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDanmakusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractServer).GetDanmakus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interact_GetDanmakus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractServer).GetDanmakus(ctx, req.(*GetDanmakusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Interact_ServiceDesc is the grpc.ServiceDesc for Interact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interact.Interact",
	HandlerType: (*InteractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _Interact_Like_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _Interact_Unlike_Handler,
		},
		{
			MethodName: "GetLikeStatus",
			Handler:    _Interact_GetLikeStatus_Handler,
		},
		{
			MethodName: "Favorite",
			Handler:    _Interact_Favorite_Handler,
		},
		{
			MethodName: "Unfavorite",
			Handler:    _Interact_Unfavorite_Handler,
		},
		{
			MethodName: "GetFavoriteStatus",
			Handler:    _Interact_GetFavoriteStatus_Handler,
		},
		{
			MethodName: "PostComment",
			Handler:    _Interact_PostComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Interact_ListComments_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Interact_DeleteComment_Handler,
		},
		{
			MethodName: "SendDanmaku",
			Handler:    _Interact_SendDanmaku_Handler,
		},
		{
			MethodName: "GetDanmakus",
			Handler:    _Interact_GetDanmakus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/interact/interact.proto",
}
