// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: transcode.proto

package server

import (
	"context"

	"gopan/rpc/transcode/internal/logic"
	"gopan/rpc/transcode/internal/svc"
	"gopan/rpc/transcode/transcode"
)

type TranscodeServer struct {
	svcCtx *svc.ServiceContext
	transcode.UnimplementedTranscodeServer
}

func NewTranscodeServer(svcCtx *svc.ServiceContext) *TranscodeServer {
	return &TranscodeServer{
		svcCtx: svcCtx,
	}
}

// 提交转码任务
func (s *TranscodeServer) SubmitTask(ctx context.Context, in *transcode.SubmitTaskReq) (*transcode.SubmitTaskResp, error) {
	l := logic.NewSubmitTaskLogic(ctx, s.svcCtx)
	return l.SubmitTask(in)
}

// 查询转码状态
func (s *TranscodeServer) QueryTask(ctx context.Context, in *transcode.QueryTaskReq) (*transcode.QueryTaskResp, error) {
	l := logic.NewQueryTaskLogic(ctx, s.svcCtx)
	return l.QueryTask(in)
}
