// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package server

import (
	"context"

	"gopan/rpc/video/internal/logic"
	"gopan/rpc/video/internal/svc"
	"gopan/rpc/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 初始化上传（返回 upload_id，创建视频记录）
func (s *VideoServer) InitUpload(ctx context.Context, in *video.InitUploadReq) (*video.InitUploadResp, error) {
	l := logic.NewInitUploadLogic(ctx, s.svcCtx)
	return l.InitUpload(in)
}

// 上传单个分片（非 stream，每个 chunk 独立 RPC）
func (s *VideoServer) UploadChunk(ctx context.Context, in *video.UploadChunkReq) (*video.UploadChunkResp, error) {
	l := logic.NewUploadChunkLogic(ctx, s.svcCtx)
	return l.UploadChunk(in)
}

// 查询上传进度（已收到的 chunk 列表）
func (s *VideoServer) UploadStatus(ctx context.Context, in *video.UploadStatusReq) (*video.UploadStatusResp, error) {
	l := logic.NewUploadStatusLogic(ctx, s.svcCtx)
	return l.UploadStatus(in)
}

// 合并分片（合并前校验完整性）
func (s *VideoServer) MergeChunks(ctx context.Context, in *video.MergeChunksReq) (*video.MergeChunksResp, error) {
	l := logic.NewMergeChunksLogic(ctx, s.svcCtx)
	return l.MergeChunks(in)
}

// 获取视频列表
func (s *VideoServer) ListVideos(ctx context.Context, in *video.ListVideosReq) (*video.ListVideosResp, error) {
	l := logic.NewListVideosLogic(ctx, s.svcCtx)
	return l.ListVideos(in)
}

// 获取视频详情
func (s *VideoServer) GetVideo(ctx context.Context, in *video.GetVideoReq) (*video.GetVideoResp, error) {
	l := logic.NewGetVideoLogic(ctx, s.svcCtx)
	return l.GetVideo(in)
}

// 更新视频信息
func (s *VideoServer) UpdateVideo(ctx context.Context, in *video.UpdateVideoReq) (*video.UpdateVideoResp, error) {
	l := logic.NewUpdateVideoLogic(ctx, s.svcCtx)
	return l.UpdateVideo(in)
}

// 删除视频
func (s *VideoServer) DeleteVideo(ctx context.Context, in *video.DeleteVideoReq) (*video.DeleteVideoResp, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}

// 转码完成回调
func (s *VideoServer) TranscodeCallback(ctx context.Context, in *video.TranscodeCallbackReq) (*video.TranscodeCallbackResp, error) {
	l := logic.NewTranscodeCallbackLogic(ctx, s.svcCtx)
	return l.TranscodeCallback(in)
}

// 获取用户视频列表
func (s *VideoServer) ListUserVideos(ctx context.Context, in *video.ListUserVideosReq) (*video.ListVideosResp, error) {
	l := logic.NewListUserVideosLogic(ctx, s.svcCtx)
	return l.ListUserVideos(in)
}
