// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package server

import (
	"context"

	"gopan/rpc/video/internal/logic"
	"gopan/rpc/video/internal/svc"
	"gopan/rpc/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 上传视频(分片)
func (s *VideoServer) UploadChunk(stream video.Video_UploadChunkServer) error {
	l := logic.NewUploadChunkLogic(stream.Context(), s.svcCtx)
	return l.UploadChunk(stream)
}

// 合并分片
func (s *VideoServer) MergeChunks(ctx context.Context, in *video.MergeChunksReq) (*video.MergeChunksResp, error) {
	l := logic.NewMergeChunksLogic(ctx, s.svcCtx)
	return l.MergeChunks(in)
}

// 获取视频列表
func (s *VideoServer) ListVideos(ctx context.Context, in *video.ListVideosReq) (*video.ListVideosResp, error) {
	l := logic.NewListVideosLogic(ctx, s.svcCtx)
	return l.ListVideos(in)
}

// 获取视频详情
func (s *VideoServer) GetVideo(ctx context.Context, in *video.GetVideoReq) (*video.GetVideoResp, error) {
	l := logic.NewGetVideoLogic(ctx, s.svcCtx)
	return l.GetVideo(in)
}

// 更新视频信息
func (s *VideoServer) UpdateVideo(ctx context.Context, in *video.UpdateVideoReq) (*video.UpdateVideoResp, error) {
	l := logic.NewUpdateVideoLogic(ctx, s.svcCtx)
	return l.UpdateVideo(in)
}

// 删除视频
func (s *VideoServer) DeleteVideo(ctx context.Context, in *video.DeleteVideoReq) (*video.DeleteVideoResp, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}

// 转码完成回调
func (s *VideoServer) TranscodeCallback(ctx context.Context, in *video.TranscodeCallbackReq) (*video.TranscodeCallbackResp, error) {
	l := logic.NewTranscodeCallbackLogic(ctx, s.svcCtx)
	return l.TranscodeCallback(in)
}

// 获取用户视频列表
func (s *VideoServer) ListUserVideos(ctx context.Context, in *video.ListUserVideosReq) (*video.ListVideosResp, error) {
	l := logic.NewListUserVideosLogic(ctx, s.svcCtx)
	return l.ListUserVideos(in)
}
