// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interact.proto

package server

import (
	"context"

	"gopan/rpc/interact/interact"
	"gopan/rpc/interact/internal/logic"
	"gopan/rpc/interact/internal/svc"
)

type InteractServer struct {
	svcCtx *svc.ServiceContext
	interact.UnimplementedInteractServer
}

func NewInteractServer(svcCtx *svc.ServiceContext) *InteractServer {
	return &InteractServer{
		svcCtx: svcCtx,
	}
}

// 点赞
func (s *InteractServer) Like(ctx context.Context, in *interact.LikeReq) (*interact.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 取消点赞
func (s *InteractServer) Unlike(ctx context.Context, in *interact.UnlikeReq) (*interact.UnlikeResp, error) {
	l := logic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

// 获取点赞状态
func (s *InteractServer) GetLikeStatus(ctx context.Context, in *interact.GetLikeStatusReq) (*interact.GetLikeStatusResp, error) {
	l := logic.NewGetLikeStatusLogic(ctx, s.svcCtx)
	return l.GetLikeStatus(in)
}

// 收藏
func (s *InteractServer) Favorite(ctx context.Context, in *interact.FavoriteReq) (*interact.FavoriteResp, error) {
	l := logic.NewFavoriteLogic(ctx, s.svcCtx)
	return l.Favorite(in)
}

// 取消收藏
func (s *InteractServer) Unfavorite(ctx context.Context, in *interact.UnfavoriteReq) (*interact.UnfavoriteResp, error) {
	l := logic.NewUnfavoriteLogic(ctx, s.svcCtx)
	return l.Unfavorite(in)
}

// 获取收藏状态
func (s *InteractServer) GetFavoriteStatus(ctx context.Context, in *interact.GetFavoriteStatusReq) (*interact.GetFavoriteStatusResp, error) {
	l := logic.NewGetFavoriteStatusLogic(ctx, s.svcCtx)
	return l.GetFavoriteStatus(in)
}

// 发送评论
func (s *InteractServer) PostComment(ctx context.Context, in *interact.PostCommentReq) (*interact.PostCommentResp, error) {
	l := logic.NewPostCommentLogic(ctx, s.svcCtx)
	return l.PostComment(in)
}

// 获取评论列表
func (s *InteractServer) ListComments(ctx context.Context, in *interact.ListCommentsReq) (*interact.ListCommentsResp, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

// 删除评论
func (s *InteractServer) DeleteComment(ctx context.Context, in *interact.DeleteCommentReq) (*interact.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 发送弹幕
func (s *InteractServer) SendDanmaku(ctx context.Context, in *interact.SendDanmakuReq) (*interact.SendDanmakuResp, error) {
	l := logic.NewSendDanmakuLogic(ctx, s.svcCtx)
	return l.SendDanmaku(in)
}

// 获取弹幕列表
func (s *InteractServer) GetDanmakus(ctx context.Context, in *interact.GetDanmakusReq) (*interact.GetDanmakusResp, error) {
	l := logic.NewGetDanmakusLogic(ctx, s.svcCtx)
	return l.GetDanmakus(in)
}
