// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package server

import (
	"context"

	"gopan/rpc/admin/admin"
	"gopan/rpc/admin/internal/logic"
	"gopan/rpc/admin/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) AdminLogin(ctx context.Context, in *admin.AdminLoginReq) (*admin.AdminLoginResp, error) {
	l := logic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

func (s *AdminServer) ListVideos(ctx context.Context, in *admin.AdminListVideosReq) (*admin.AdminListVideosResp, error) {
	l := logic.NewListVideosLogic(ctx, s.svcCtx)
	return l.ListVideos(in)
}

func (s *AdminServer) ApproveVideo(ctx context.Context, in *admin.ApproveVideoReq) (*admin.ApproveVideoResp, error) {
	l := logic.NewApproveVideoLogic(ctx, s.svcCtx)
	return l.ApproveVideo(in)
}

func (s *AdminServer) RejectVideo(ctx context.Context, in *admin.RejectVideoReq) (*admin.RejectVideoResp, error) {
	l := logic.NewRejectVideoLogic(ctx, s.svcCtx)
	return l.RejectVideo(in)
}

func (s *AdminServer) DeleteVideo(ctx context.Context, in *admin.AdminDeleteVideoReq) (*admin.AdminDeleteVideoResp, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}
