// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interact.proto

package interactclient

import (
	"context"

	"gopan/rpc/interact/interact"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo           = interact.CommentInfo
	DanmakuInfo           = interact.DanmakuInfo
	DeleteCommentReq      = interact.DeleteCommentReq
	DeleteCommentResp     = interact.DeleteCommentResp
	FavoriteReq           = interact.FavoriteReq
	FavoriteResp          = interact.FavoriteResp
	GetDanmakusReq        = interact.GetDanmakusReq
	GetDanmakusResp       = interact.GetDanmakusResp
	GetFavoriteStatusReq  = interact.GetFavoriteStatusReq
	GetFavoriteStatusResp = interact.GetFavoriteStatusResp
	GetLikeStatusReq      = interact.GetLikeStatusReq
	GetLikeStatusResp     = interact.GetLikeStatusResp
	LikeReq               = interact.LikeReq
	LikeResp              = interact.LikeResp
	ListCommentsReq       = interact.ListCommentsReq
	ListCommentsResp      = interact.ListCommentsResp
	PostCommentReq        = interact.PostCommentReq
	PostCommentResp       = interact.PostCommentResp
	SendDanmakuReq        = interact.SendDanmakuReq
	SendDanmakuResp       = interact.SendDanmakuResp
	UnfavoriteReq         = interact.UnfavoriteReq
	UnfavoriteResp        = interact.UnfavoriteResp
	UnlikeReq             = interact.UnlikeReq
	UnlikeResp            = interact.UnlikeResp

	Interact interface {
		// 点赞
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
		// 取消点赞
		Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error)
		// 获取点赞状态
		GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error)
		// 收藏
		Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error)
		// 取消收藏
		Unfavorite(ctx context.Context, in *UnfavoriteReq, opts ...grpc.CallOption) (*UnfavoriteResp, error)
		// 获取收藏状态
		GetFavoriteStatus(ctx context.Context, in *GetFavoriteStatusReq, opts ...grpc.CallOption) (*GetFavoriteStatusResp, error)
		// 发送评论
		PostComment(ctx context.Context, in *PostCommentReq, opts ...grpc.CallOption) (*PostCommentResp, error)
		// 获取评论列表
		ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
		// 删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		// 发送弹幕
		SendDanmaku(ctx context.Context, in *SendDanmakuReq, opts ...grpc.CallOption) (*SendDanmakuResp, error)
		// 获取弹幕列表
		GetDanmakus(ctx context.Context, in *GetDanmakusReq, opts ...grpc.CallOption) (*GetDanmakusResp, error)
	}

	defaultInteract struct {
		cli zrpc.Client
	}
)

func NewInteract(cli zrpc.Client) Interact {
	return &defaultInteract{
		cli: cli,
	}
}

// 点赞
func (m *defaultInteract) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 取消点赞
func (m *defaultInteract) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.Unlike(ctx, in, opts...)
}

// 获取点赞状态
func (m *defaultInteract) GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.GetLikeStatus(ctx, in, opts...)
}

// 收藏
func (m *defaultInteract) Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

// 取消收藏
func (m *defaultInteract) Unfavorite(ctx context.Context, in *UnfavoriteReq, opts ...grpc.CallOption) (*UnfavoriteResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.Unfavorite(ctx, in, opts...)
}

// 获取收藏状态
func (m *defaultInteract) GetFavoriteStatus(ctx context.Context, in *GetFavoriteStatusReq, opts ...grpc.CallOption) (*GetFavoriteStatusResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.GetFavoriteStatus(ctx, in, opts...)
}

// 发送评论
func (m *defaultInteract) PostComment(ctx context.Context, in *PostCommentReq, opts ...grpc.CallOption) (*PostCommentResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.PostComment(ctx, in, opts...)
}

// 获取评论列表
func (m *defaultInteract) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

// 删除评论
func (m *defaultInteract) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 发送弹幕
func (m *defaultInteract) SendDanmaku(ctx context.Context, in *SendDanmakuReq, opts ...grpc.CallOption) (*SendDanmakuResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.SendDanmaku(ctx, in, opts...)
}

// 获取弹幕列表
func (m *defaultInteract) GetDanmakus(ctx context.Context, in *GetDanmakusReq, opts ...grpc.CallOption) (*GetDanmakusResp, error) {
	client := interact.NewInteractClient(m.cli.Conn())
	return client.GetDanmakus(ctx, in, opts...)
}
