// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: rpc/stream/stream.proto

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stream_GetPlayUrl_FullMethodName    = "/stream.Stream/GetPlayUrl"
	Stream_IncrPlayCount_FullMethodName = "/stream.Stream/IncrPlayCount"
)

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 流媒体服务
type StreamClient interface {
	// 获取播放地址(带防盗链签名)
	GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error)
	// 增加播放计数
	IncrPlayCount(ctx context.Context, in *IncrPlayCountReq, opts ...grpc.CallOption) (*IncrPlayCountResp, error)
}

type streamClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamClient(cc grpc.ClientConnInterface) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayUrlResp)
	err := c.cc.Invoke(ctx, Stream_GetPlayUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamClient) IncrPlayCount(ctx context.Context, in *IncrPlayCountReq, opts ...grpc.CallOption) (*IncrPlayCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrPlayCountResp)
	err := c.cc.Invoke(ctx, Stream_IncrPlayCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServer is the server API for Stream service.
// All implementations must embed UnimplementedStreamServer
// for forward compatibility.
//
// 流媒体服务
type StreamServer interface {
	// 获取播放地址(带防盗链签名)
	GetPlayUrl(context.Context, *GetPlayUrlReq) (*GetPlayUrlResp, error)
	// 增加播放计数
	IncrPlayCount(context.Context, *IncrPlayCountReq) (*IncrPlayCountResp, error)
	mustEmbedUnimplementedStreamServer()
}

// UnimplementedStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServer struct{}

func (UnimplementedStreamServer) GetPlayUrl(context.Context, *GetPlayUrlReq) (*GetPlayUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayUrl not implemented")
}
func (UnimplementedStreamServer) IncrPlayCount(context.Context, *IncrPlayCountReq) (*IncrPlayCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrPlayCount not implemented")
}
func (UnimplementedStreamServer) mustEmbedUnimplementedStreamServer() {}
func (UnimplementedStreamServer) testEmbeddedByValue()                {}

// UnsafeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServer will
// result in compilation errors.
type UnsafeStreamServer interface {
	mustEmbedUnimplementedStreamServer()
}

func RegisterStreamServer(s grpc.ServiceRegistrar, srv StreamServer) {
	// If the following call panics, it indicates UnimplementedStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stream_ServiceDesc, srv)
}

func _Stream_GetPlayUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServer).GetPlayUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stream_GetPlayUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServer).GetPlayUrl(ctx, req.(*GetPlayUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stream_IncrPlayCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrPlayCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServer).IncrPlayCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stream_IncrPlayCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServer).IncrPlayCount(ctx, req.(*IncrPlayCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Stream_ServiceDesc is the grpc.ServiceDesc for Stream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayUrl",
			Handler:    _Stream_GetPlayUrl_Handler,
		},
		{
			MethodName: "IncrPlayCount",
			Handler:    _Stream_IncrPlayCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/stream/stream.proto",
}
