// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "gopan/gateway/internal/handler/admin"
	search "gopan/gateway/internal/handler/search"
	user "gopan/gateway/internal/handler/user"
	video "gopan/gateway/internal/handler/video"
	"gopan/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: admin.AdminLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/videos",
				Handler: admin.AdminListVideosHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/approve",
				Handler: admin.ApproveVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reject",
				Handler: admin.RejectVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/video",
				Handler: admin.DeleteVideoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/videos",
				Handler: search.SearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/search"),
	)

	// 测试路由：与 /api/video/list 完全一致，但不挂限流中间件，用于压测对比
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: video.ListVideosHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/test"),
	)

	// 视频列表和详情公开访问（带限流保护）
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimiterList},
			rest.Route{Method: http.MethodGet, Path: "/list", Handler: video.ListVideosHandler(serverCtx)},
		),
		rest.WithPrefix("/api/video"),
	)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimiterDetail},
			rest.Route{Method: http.MethodGet, Path: "/detail", Handler: video.GetVideoHandler(serverCtx)},
		),
		rest.WithPrefix("/api/video"),
	)

	// 登录: 公开访问但需要防撞库限流
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimiterLogin},
			rest.Route{Method: http.MethodPost, Path: "/login", Handler: user.LoginHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/register", Handler: user.RegisterHandler(serverCtx)},
		),
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: user.GetProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/profile",
				Handler: user.UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/comment",
					Handler: video.PostCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/comment",
					Handler: video.DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/comments",
					Handler: video.ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/danmaku",
					Handler: video.SendDanmakuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/danmakus",
					Handler: video.GetDanmakusHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delete",
					Handler: video.DeleteVideoHandler(serverCtx),
				},
					{
						Method:  http.MethodPost,
					Path:    "/favorite",
					Handler: video.FavoriteVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/favorite",
					Handler: video.UnfavoriteVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/init-upload",
					Handler: video.InitUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/like",
					Handler: video.LikeVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/like",
					Handler: video.UnlikeVideoHandler(serverCtx),
				},
					{
						Method:  http.MethodPost,
						Path:    "/merge-chunks",
					Handler: video.MergeChunksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/play-progress",
					Handler: video.SavePlayProgressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/play-progress",
					Handler: video.GetPlayProgressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/play-url",
					Handler: video.GetPlayUrlHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/update",
					Handler: video.UpdateVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload-chunk",
					Handler: video.UploadChunkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/upload-status",
					Handler: video.UploadStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/video"),
	)
}
