// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package server

import (
	"context"

	"gopan/rpc/search/internal/logic"
	"gopan/rpc/search/internal/svc"
	"gopan/rpc/search/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

// 搜索视频
func (s *SearchServer) SearchVideos(ctx context.Context, in *search.SearchVideosReq) (*search.SearchVideosResp, error) {
	l := logic.NewSearchVideosLogic(ctx, s.svcCtx)
	return l.SearchVideos(in)
}

// 索引视频(创建/更新)
func (s *SearchServer) IndexVideo(ctx context.Context, in *search.IndexVideoReq) (*search.IndexVideoResp, error) {
	l := logic.NewIndexVideoLogic(ctx, s.svcCtx)
	return l.IndexVideo(in)
}

// 从索引中移除
func (s *SearchServer) RemoveVideo(ctx context.Context, in *search.RemoveVideoReq) (*search.RemoveVideoResp, error) {
	l := logic.NewRemoveVideoLogic(ctx, s.svcCtx)
	return l.RemoveVideo(in)
}
