// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/video/video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── InitUpload ───
type InitUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                           // 原始文件名
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                 // 视频标题
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`          // 文件总大小（字节）
	TotalChunks   int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"` // 总分片数
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 上传者用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadReq) Reset() {
	*x = InitUploadReq{}
	mi := &file_rpc_video_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadReq) ProtoMessage() {}

func (x *InitUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadReq.ProtoReflect.Descriptor instead.
func (*InitUploadReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{0}
}

func (x *InitUploadReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitUploadReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InitUploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *InitUploadReq) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *InitUploadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InitUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`   // 分配的视频 ID
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"` // 上传会话 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadResp) Reset() {
	*x = InitUploadResp{}
	mi := &file_rpc_video_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadResp) ProtoMessage() {}

func (x *InitUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadResp.ProtoReflect.Descriptor instead.
func (*InitUploadResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{1}
}

func (x *InitUploadResp) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *InitUploadResp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// ─── UploadChunk ───
type UploadChunkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`        // 上传会话 ID
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频 ID
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // 分片序号（从 0 开始）
	FileSize      int32                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`       // 分片字节数
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                // 分片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkReq) Reset() {
	*x = UploadChunkReq{}
	mi := &file_rpc_video_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkReq) ProtoMessage() {}

func (x *UploadChunkReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkReq.ProtoReflect.Descriptor instead.
func (*UploadChunkReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{2}
}

func (x *UploadChunkReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadChunkReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UploadChunkReq) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkReq) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadChunkReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedIndex int32                  `protobuf:"varint,1,opt,name=received_index,json=receivedIndex,proto3" json:"received_index,omitempty"` // 已接收的分片序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkResp) Reset() {
	*x = UploadChunkResp{}
	mi := &file_rpc_video_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkResp) ProtoMessage() {}

func (x *UploadChunkResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkResp.ProtoReflect.Descriptor instead.
func (*UploadChunkResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{3}
}

func (x *UploadChunkResp) GetReceivedIndex() int32 {
	if x != nil {
		return x.ReceivedIndex
	}
	return 0
}

// ─── UploadStatus ───
type UploadStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatusReq) Reset() {
	*x = UploadStatusReq{}
	mi := &file_rpc_video_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusReq) ProtoMessage() {}

func (x *UploadStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusReq.ProtoReflect.Descriptor instead.
func (*UploadStatusReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{4}
}

func (x *UploadStatusReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type UploadStatusResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	TotalChunks    int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	ReceivedChunks []int32                `protobuf:"varint,3,rep,packed,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadStatusResp) Reset() {
	*x = UploadStatusResp{}
	mi := &file_rpc_video_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusResp) ProtoMessage() {}

func (x *UploadStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusResp.ProtoReflect.Descriptor instead.
func (*UploadStatusResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{5}
}

func (x *UploadStatusResp) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UploadStatusResp) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadStatusResp) GetReceivedChunks() []int32 {
	if x != nil {
		return x.ReceivedChunks
	}
	return nil
}

// ─── MergeChunks ───
type MergeChunksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChunksReq) Reset() {
	*x = MergeChunksReq{}
	mi := &file_rpc_video_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChunksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChunksReq) ProtoMessage() {}

func (x *MergeChunksReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChunksReq.ProtoReflect.Descriptor instead.
func (*MergeChunksReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{6}
}

func (x *MergeChunksReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *MergeChunksReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type MergeChunksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                            // "complete" / "incomplete"
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`                     // 合并后的源文件 MinIO key
	FileHash      string                 `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`                        // 文件哈希（用于秒传）
	MissingChunks []int32                `protobuf:"varint,4,rep,packed,name=missing_chunks,json=missingChunks,proto3" json:"missing_chunks,omitempty"` // 缺失的分片序号列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChunksResp) Reset() {
	*x = MergeChunksResp{}
	mi := &file_rpc_video_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChunksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChunksResp) ProtoMessage() {}

func (x *MergeChunksResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChunksResp.ProtoReflect.Descriptor instead.
func (*MergeChunksResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{7}
}

func (x *MergeChunksResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MergeChunksResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *MergeChunksResp) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *MergeChunksResp) GetMissingChunks() []int32 {
	if x != nil {
		return x.MissingChunks
	}
	return nil
}

// ─── List / Get ───
type ListVideosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"` // newest / hot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosReq) Reset() {
	*x = ListVideosReq{}
	mi := &file_rpc_video_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosReq) ProtoMessage() {}

func (x *ListVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosReq.ProtoReflect.Descriptor instead.
func (*ListVideosReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{8}
}

func (x *ListVideosReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListVideosReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVideosReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListVideosReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListVideosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResp) Reset() {
	*x = ListVideosResp{}
	mi := &file_rpc_video_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResp) ProtoMessage() {}

func (x *ListVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResp.ProtoReflect.Descriptor instead.
func (*ListVideosResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{9}
}

func (x *ListVideosResp) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideosResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ListVideosResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	PlayCount     int64                  `protobuf:"varint,6,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"` // 0:上传中 1:转码中 2:正常 3:失败 4:已下架
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Transcodes    []*TranscodeInfo       `protobuf:"bytes,11,rep,name=transcodes,proto3" json:"transcodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_rpc_video_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideoInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *VideoInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VideoInfo) GetTranscodes() []*TranscodeInfo {
	if x != nil {
		return x.Transcodes
	}
	return nil
}

type TranscodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	M3U8Url       string                 `protobuf:"bytes,2,opt,name=m3u8_url,json=m3u8Url,proto3" json:"m3u8_url,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeInfo) Reset() {
	*x = TranscodeInfo{}
	mi := &file_rpc_video_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeInfo) ProtoMessage() {}

func (x *TranscodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeInfo.ProtoReflect.Descriptor instead.
func (*TranscodeInfo) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{11}
}

func (x *TranscodeInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *TranscodeInfo) GetM3U8Url() string {
	if x != nil {
		return x.M3U8Url
	}
	return ""
}

func (x *TranscodeInfo) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type GetVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoReq) Reset() {
	*x = GetVideoReq{}
	mi := &file_rpc_video_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReq) ProtoMessage() {}

func (x *GetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReq.ProtoReflect.Descriptor instead.
func (*GetVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{12}
}

func (x *GetVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoInfo             `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResp) Reset() {
	*x = GetVideoResp{}
	mi := &file_rpc_video_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResp) ProtoMessage() {}

func (x *GetVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResp.ProtoReflect.Descriptor instead.
func (*GetVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{13}
}

func (x *GetVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

type UpdateVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoReq) Reset() {
	*x = UpdateVideoReq{}
	mi := &file_rpc_video_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoReq) ProtoMessage() {}

func (x *UpdateVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoReq.ProtoReflect.Descriptor instead.
func (*UpdateVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UpdateVideoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVideoReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoResp) Reset() {
	*x = UpdateVideoResp{}
	mi := &file_rpc_video_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoResp) ProtoMessage() {}

func (x *UpdateVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoResp.ProtoReflect.Descriptor instead.
func (*UpdateVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{15}
}

type DeleteVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoReq) Reset() {
	*x = DeleteVideoReq{}
	mi := &file_rpc_video_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoReq) ProtoMessage() {}

func (x *DeleteVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoReq.ProtoReflect.Descriptor instead.
func (*DeleteVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DeleteVideoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResp) Reset() {
	*x = DeleteVideoResp{}
	mi := &file_rpc_video_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResp) ProtoMessage() {}

func (x *DeleteVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResp.ProtoReflect.Descriptor instead.
func (*DeleteVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{17}
}

type TranscodeCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 2:成功 3:失败
	Transcodes    []*TranscodeInfo       `protobuf:"bytes,3,rep,name=transcodes,proto3" json:"transcodes,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeCallbackReq) Reset() {
	*x = TranscodeCallbackReq{}
	mi := &file_rpc_video_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeCallbackReq) ProtoMessage() {}

func (x *TranscodeCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeCallbackReq.ProtoReflect.Descriptor instead.
func (*TranscodeCallbackReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{18}
}

func (x *TranscodeCallbackReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *TranscodeCallbackReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TranscodeCallbackReq) GetTranscodes() []*TranscodeInfo {
	if x != nil {
		return x.Transcodes
	}
	return nil
}

func (x *TranscodeCallbackReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *TranscodeCallbackReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TranscodeCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeCallbackResp) Reset() {
	*x = TranscodeCallbackResp{}
	mi := &file_rpc_video_video_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeCallbackResp) ProtoMessage() {}

func (x *TranscodeCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeCallbackResp.ProtoReflect.Descriptor instead.
func (*TranscodeCallbackResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{19}
}

type ListUserVideosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserVideosReq) Reset() {
	*x = ListUserVideosReq{}
	mi := &file_rpc_video_video_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserVideosReq) ProtoMessage() {}

func (x *ListUserVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_video_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserVideosReq.ProtoReflect.Descriptor instead.
func (*ListUserVideosReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_video_proto_rawDescGZIP(), []int{20}
}

func (x *ListUserVideosReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserVideosReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListUserVideosReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_rpc_video_video_proto protoreflect.FileDescriptor

const file_rpc_video_video_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/video/video.proto\x12\x05video\"\x9a\x01\n" +
	"\rInitUploadReq\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"H\n" +
	"\x0eInitUploadResp\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"\x9a\x01\n" +
	"\x0eUploadChunkReq\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x05R\bfileSize\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"8\n" +
	"\x0fUploadChunkResp\x12%\n" +
	"\x0ereceived_index\x18\x01 \x01(\x05R\rreceivedIndex\".\n" +
	"\x0fUploadStatusReq\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"y\n" +
	"\x10UploadStatusResp\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12'\n" +
	"\x0freceived_chunks\x18\x03 \x03(\x05R\x0ereceivedChunks\"H\n" +
	"\x0eMergeChunksReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"\x8c\x01\n" +
	"\x0fMergeChunksResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tfile_hash\x18\x03 \x01(\tR\bfileHash\x12%\n" +
	"\x0emissing_chunks\x18\x04 \x03(\x05R\rmissingChunks\"m\n" +
	"\rListVideosReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"v\n" +
	"\x0eListVideosResp\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xca\x02\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"play_count\x18\x06 \x01(\x03R\tplayCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x124\n" +
	"\n" +
	"transcodes\x18\v \x03(\v2\x14.video.TranscodeInfoR\n" +
	"transcodes\"d\n" +
	"\rTranscodeInfo\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\x12\x19\n" +
	"\bm3u8_url\x18\x02 \x01(\tR\am3u8Url\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\"(\n" +
	"\vGetVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"6\n" +
	"\fGetVideoResp\x12&\n" +
	"\x05video\x18\x01 \x01(\v2\x10.video.VideoInfoR\x05video\"\x98\x01\n" +
	"\x0eUpdateVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\x11\n" +
	"\x0fUpdateVideoResp\"D\n" +
	"\x0eDeleteVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x11\n" +
	"\x0fDeleteVideoResp\"\xb8\x01\n" +
	"\x14TranscodeCallbackReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x124\n" +
	"\n" +
	"transcodes\x18\x03 \x03(\v2\x14.video.TranscodeInfoR\n" +
	"transcodes\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\"\x17\n" +
	"\x15TranscodeCallbackResp\"Z\n" +
	"\x11ListUserVideosReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit2\xfe\x04\n" +
	"\x05Video\x129\n" +
	"\n" +
	"InitUpload\x12\x14.video.InitUploadReq\x1a\x15.video.InitUploadResp\x12<\n" +
	"\vUploadChunk\x12\x15.video.UploadChunkReq\x1a\x16.video.UploadChunkResp\x12?\n" +
	"\fUploadStatus\x12\x16.video.UploadStatusReq\x1a\x17.video.UploadStatusResp\x12<\n" +
	"\vMergeChunks\x12\x15.video.MergeChunksReq\x1a\x16.video.MergeChunksResp\x129\n" +
	"\n" +
	"ListVideos\x12\x14.video.ListVideosReq\x1a\x15.video.ListVideosResp\x123\n" +
	"\bGetVideo\x12\x12.video.GetVideoReq\x1a\x13.video.GetVideoResp\x12<\n" +
	"\vUpdateVideo\x12\x15.video.UpdateVideoReq\x1a\x16.video.UpdateVideoResp\x12<\n" +
	"\vDeleteVideo\x12\x15.video.DeleteVideoReq\x1a\x16.video.DeleteVideoResp\x12N\n" +
	"\x11TranscodeCallback\x12\x1b.video.TranscodeCallbackReq\x1a\x1c.video.TranscodeCallbackResp\x12A\n" +
	"\x0eListUserVideos\x12\x18.video.ListUserVideosReq\x1a\x15.video.ListVideosRespB\tZ\a./videob\x06proto3"

var (
	file_rpc_video_video_proto_rawDescOnce sync.Once
	file_rpc_video_video_proto_rawDescData []byte
)

func file_rpc_video_video_proto_rawDescGZIP() []byte {
	file_rpc_video_video_proto_rawDescOnce.Do(func() {
		file_rpc_video_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_video_video_proto_rawDesc), len(file_rpc_video_video_proto_rawDesc)))
	})
	return file_rpc_video_video_proto_rawDescData
}

var file_rpc_video_video_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_rpc_video_video_proto_goTypes = []any{
	(*InitUploadReq)(nil),         // 0: video.InitUploadReq
	(*InitUploadResp)(nil),        // 1: video.InitUploadResp
	(*UploadChunkReq)(nil),        // 2: video.UploadChunkReq
	(*UploadChunkResp)(nil),       // 3: video.UploadChunkResp
	(*UploadStatusReq)(nil),       // 4: video.UploadStatusReq
	(*UploadStatusResp)(nil),      // 5: video.UploadStatusResp
	(*MergeChunksReq)(nil),        // 6: video.MergeChunksReq
	(*MergeChunksResp)(nil),       // 7: video.MergeChunksResp
	(*ListVideosReq)(nil),         // 8: video.ListVideosReq
	(*ListVideosResp)(nil),        // 9: video.ListVideosResp
	(*VideoInfo)(nil),             // 10: video.VideoInfo
	(*TranscodeInfo)(nil),         // 11: video.TranscodeInfo
	(*GetVideoReq)(nil),           // 12: video.GetVideoReq
	(*GetVideoResp)(nil),          // 13: video.GetVideoResp
	(*UpdateVideoReq)(nil),        // 14: video.UpdateVideoReq
	(*UpdateVideoResp)(nil),       // 15: video.UpdateVideoResp
	(*DeleteVideoReq)(nil),        // 16: video.DeleteVideoReq
	(*DeleteVideoResp)(nil),       // 17: video.DeleteVideoResp
	(*TranscodeCallbackReq)(nil),  // 18: video.TranscodeCallbackReq
	(*TranscodeCallbackResp)(nil), // 19: video.TranscodeCallbackResp
	(*ListUserVideosReq)(nil),     // 20: video.ListUserVideosReq
}
var file_rpc_video_video_proto_depIdxs = []int32{
	10, // 0: video.ListVideosResp.videos:type_name -> video.VideoInfo
	11, // 1: video.VideoInfo.transcodes:type_name -> video.TranscodeInfo
	10, // 2: video.GetVideoResp.video:type_name -> video.VideoInfo
	11, // 3: video.TranscodeCallbackReq.transcodes:type_name -> video.TranscodeInfo
	0,  // 4: video.Video.InitUpload:input_type -> video.InitUploadReq
	2,  // 5: video.Video.UploadChunk:input_type -> video.UploadChunkReq
	4,  // 6: video.Video.UploadStatus:input_type -> video.UploadStatusReq
	6,  // 7: video.Video.MergeChunks:input_type -> video.MergeChunksReq
	8,  // 8: video.Video.ListVideos:input_type -> video.ListVideosReq
	12, // 9: video.Video.GetVideo:input_type -> video.GetVideoReq
	14, // 10: video.Video.UpdateVideo:input_type -> video.UpdateVideoReq
	16, // 11: video.Video.DeleteVideo:input_type -> video.DeleteVideoReq
	18, // 12: video.Video.TranscodeCallback:input_type -> video.TranscodeCallbackReq
	20, // 13: video.Video.ListUserVideos:input_type -> video.ListUserVideosReq
	1,  // 14: video.Video.InitUpload:output_type -> video.InitUploadResp
	3,  // 15: video.Video.UploadChunk:output_type -> video.UploadChunkResp
	5,  // 16: video.Video.UploadStatus:output_type -> video.UploadStatusResp
	7,  // 17: video.Video.MergeChunks:output_type -> video.MergeChunksResp
	9,  // 18: video.Video.ListVideos:output_type -> video.ListVideosResp
	13, // 19: video.Video.GetVideo:output_type -> video.GetVideoResp
	15, // 20: video.Video.UpdateVideo:output_type -> video.UpdateVideoResp
	17, // 21: video.Video.DeleteVideo:output_type -> video.DeleteVideoResp
	19, // 22: video.Video.TranscodeCallback:output_type -> video.TranscodeCallbackResp
	9,  // 23: video.Video.ListUserVideos:output_type -> video.ListVideosResp
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_video_video_proto_init() }
func file_rpc_video_video_proto_init() {
	if File_rpc_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_video_video_proto_rawDesc), len(file_rpc_video_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_video_video_proto_goTypes,
		DependencyIndexes: file_rpc_video_video_proto_depIdxs,
		MessageInfos:      file_rpc_video_video_proto_msgTypes,
	}.Build()
	File_rpc_video_video_proto = out.File
	file_rpc_video_video_proto_goTypes = nil
	file_rpc_video_video_proto_depIdxs = nil
}
