// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Video_InitUpload_FullMethodName        = "/video.Video/InitUpload"
	Video_UploadChunk_FullMethodName       = "/video.Video/UploadChunk"
	Video_UploadStatus_FullMethodName      = "/video.Video/UploadStatus"
	Video_MergeChunks_FullMethodName       = "/video.Video/MergeChunks"
	Video_ListVideos_FullMethodName        = "/video.Video/ListVideos"
	Video_GetVideo_FullMethodName          = "/video.Video/GetVideo"
	Video_UpdateVideo_FullMethodName       = "/video.Video/UpdateVideo"
	Video_DeleteVideo_FullMethodName       = "/video.Video/DeleteVideo"
	Video_TranscodeCallback_FullMethodName = "/video.Video/TranscodeCallback"
	Video_ListUserVideos_FullMethodName    = "/video.Video/ListUserVideos"
	Video_SavePlayProgress_FullMethodName  = "/video.Video/SavePlayProgress"
	Video_GetPlayProgress_FullMethodName   = "/video.Video/GetPlayProgress"
	Video_UpdateCover_FullMethodName       = "/video.Video/UpdateCover"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频服务
type VideoClient interface {
	// 初始化上传（返回 upload_id，创建视频记录）
	InitUpload(ctx context.Context, in *InitUploadReq, opts ...grpc.CallOption) (*InitUploadResp, error)
	// 上传单个分片（非 stream，每个 chunk 独立 RPC）
	UploadChunk(ctx context.Context, in *UploadChunkReq, opts ...grpc.CallOption) (*UploadChunkResp, error)
	// 查询上传进度（已收到的 chunk 列表）
	UploadStatus(ctx context.Context, in *UploadStatusReq, opts ...grpc.CallOption) (*UploadStatusResp, error)
	// 合并分片（合并前校验完整性）
	MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error)
	// 获取视频列表
	ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
	// 获取视频详情
	GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error)
	// 更新视频信息
	UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error)
	// 删除视频
	DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
	// 转码完成回调
	TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error)
	// 获取用户视频列表
	ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
	// 保存播放进度
	SavePlayProgress(ctx context.Context, in *SavePlayProgressReq, opts ...grpc.CallOption) (*SavePlayProgressResp, error)
	// 获取播放进度
	GetPlayProgress(ctx context.Context, in *GetPlayProgressReq, opts ...grpc.CallOption) (*GetPlayProgressResp, error)
	// 更新视频封面
	UpdateCover(ctx context.Context, in *UpdateCoverReq, opts ...grpc.CallOption) (*UpdateCoverResp, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) InitUpload(ctx context.Context, in *InitUploadReq, opts ...grpc.CallOption) (*InitUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitUploadResp)
	err := c.cc.Invoke(ctx, Video_InitUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) UploadChunk(ctx context.Context, in *UploadChunkReq, opts ...grpc.CallOption) (*UploadChunkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadChunkResp)
	err := c.cc.Invoke(ctx, Video_UploadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) UploadStatus(ctx context.Context, in *UploadStatusReq, opts ...grpc.CallOption) (*UploadStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadStatusResp)
	err := c.cc.Invoke(ctx, Video_UploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeChunksResp)
	err := c.cc.Invoke(ctx, Video_MergeChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosResp)
	err := c.cc.Invoke(ctx, Video_ListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoResp)
	err := c.cc.Invoke(ctx, Video_GetVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoResp)
	err := c.cc.Invoke(ctx, Video_UpdateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVideoResp)
	err := c.cc.Invoke(ctx, Video_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscodeCallbackResp)
	err := c.cc.Invoke(ctx, Video_TranscodeCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosResp)
	err := c.cc.Invoke(ctx, Video_ListUserVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) SavePlayProgress(ctx context.Context, in *SavePlayProgressReq, opts ...grpc.CallOption) (*SavePlayProgressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavePlayProgressResp)
	err := c.cc.Invoke(ctx, Video_SavePlayProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetPlayProgress(ctx context.Context, in *GetPlayProgressReq, opts ...grpc.CallOption) (*GetPlayProgressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayProgressResp)
	err := c.cc.Invoke(ctx, Video_GetPlayProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) UpdateCover(ctx context.Context, in *UpdateCoverReq, opts ...grpc.CallOption) (*UpdateCoverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCoverResp)
	err := c.cc.Invoke(ctx, Video_UpdateCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility.
//
// 视频服务
type VideoServer interface {
	// 初始化上传（返回 upload_id，创建视频记录）
	InitUpload(context.Context, *InitUploadReq) (*InitUploadResp, error)
	// 上传单个分片（非 stream，每个 chunk 独立 RPC）
	UploadChunk(context.Context, *UploadChunkReq) (*UploadChunkResp, error)
	// 查询上传进度（已收到的 chunk 列表）
	UploadStatus(context.Context, *UploadStatusReq) (*UploadStatusResp, error)
	// 合并分片（合并前校验完整性）
	MergeChunks(context.Context, *MergeChunksReq) (*MergeChunksResp, error)
	// 获取视频列表
	ListVideos(context.Context, *ListVideosReq) (*ListVideosResp, error)
	// 获取视频详情
	GetVideo(context.Context, *GetVideoReq) (*GetVideoResp, error)
	// 更新视频信息
	UpdateVideo(context.Context, *UpdateVideoReq) (*UpdateVideoResp, error)
	// 删除视频
	DeleteVideo(context.Context, *DeleteVideoReq) (*DeleteVideoResp, error)
	// 转码完成回调
	TranscodeCallback(context.Context, *TranscodeCallbackReq) (*TranscodeCallbackResp, error)
	// 获取用户视频列表
	ListUserVideos(context.Context, *ListUserVideosReq) (*ListVideosResp, error)
	// 保存播放进度
	SavePlayProgress(context.Context, *SavePlayProgressReq) (*SavePlayProgressResp, error)
	// 获取播放进度
	GetPlayProgress(context.Context, *GetPlayProgressReq) (*GetPlayProgressResp, error)
	// 更新视频封面
	UpdateCover(context.Context, *UpdateCoverReq) (*UpdateCoverResp, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServer struct{}

func (UnimplementedVideoServer) InitUpload(context.Context, *InitUploadReq) (*InitUploadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitUpload not implemented")
}
func (UnimplementedVideoServer) UploadChunk(context.Context, *UploadChunkReq) (*UploadChunkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadChunk not implemented")
}
func (UnimplementedVideoServer) UploadStatus(context.Context, *UploadStatusReq) (*UploadStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadStatus not implemented")
}
func (UnimplementedVideoServer) MergeChunks(context.Context, *MergeChunksReq) (*MergeChunksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeChunks not implemented")
}
func (UnimplementedVideoServer) ListVideos(context.Context, *ListVideosReq) (*ListVideosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVideos not implemented")
}
func (UnimplementedVideoServer) GetVideo(context.Context, *GetVideoReq) (*GetVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideo not implemented")
}
func (UnimplementedVideoServer) UpdateVideo(context.Context, *UpdateVideoReq) (*UpdateVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVideo not implemented")
}
func (UnimplementedVideoServer) DeleteVideo(context.Context, *DeleteVideoReq) (*DeleteVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedVideoServer) TranscodeCallback(context.Context, *TranscodeCallbackReq) (*TranscodeCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscodeCallback not implemented")
}
func (UnimplementedVideoServer) ListUserVideos(context.Context, *ListUserVideosReq) (*ListVideosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserVideos not implemented")
}
func (UnimplementedVideoServer) SavePlayProgress(context.Context, *SavePlayProgressReq) (*SavePlayProgressResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePlayProgress not implemented")
}
func (UnimplementedVideoServer) GetPlayProgress(context.Context, *GetPlayProgressReq) (*GetPlayProgressResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayProgress not implemented")
}
func (UnimplementedVideoServer) UpdateCover(context.Context, *UpdateCoverReq) (*UpdateCoverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCover not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}
func (UnimplementedVideoServer) testEmbeddedByValue()               {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	// If the following call panics, it indicates UnimplementedVideoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_InitUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).InitUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_InitUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).InitUpload(ctx, req.(*InitUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_UploadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).UploadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_UploadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).UploadChunk(ctx, req.(*UploadChunkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_UploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).UploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_UploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).UploadStatus(ctx, req.(*UploadStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_MergeChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeChunksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).MergeChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_MergeChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).MergeChunks(ctx, req.(*MergeChunksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListVideos(ctx, req.(*ListVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideo(ctx, req.(*GetVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_UpdateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).UpdateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_UpdateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).UpdateVideo(ctx, req.(*UpdateVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).DeleteVideo(ctx, req.(*DeleteVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_TranscodeCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscodeCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).TranscodeCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_TranscodeCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).TranscodeCallback(ctx, req.(*TranscodeCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_ListUserVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).ListUserVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_ListUserVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).ListUserVideos(ctx, req.(*ListUserVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_SavePlayProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePlayProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).SavePlayProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_SavePlayProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).SavePlayProgress(ctx, req.(*SavePlayProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetPlayProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetPlayProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetPlayProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetPlayProgress(ctx, req.(*GetPlayProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_UpdateCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCoverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).UpdateCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_UpdateCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).UpdateCover(ctx, req.(*UpdateCoverReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitUpload",
			Handler:    _Video_InitUpload_Handler,
		},
		{
			MethodName: "UploadChunk",
			Handler:    _Video_UploadChunk_Handler,
		},
		{
			MethodName: "UploadStatus",
			Handler:    _Video_UploadStatus_Handler,
		},
		{
			MethodName: "MergeChunks",
			Handler:    _Video_MergeChunks_Handler,
		},
		{
			MethodName: "ListVideos",
			Handler:    _Video_ListVideos_Handler,
		},
		{
			MethodName: "GetVideo",
			Handler:    _Video_GetVideo_Handler,
		},
		{
			MethodName: "UpdateVideo",
			Handler:    _Video_UpdateVideo_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _Video_DeleteVideo_Handler,
		},
		{
			MethodName: "TranscodeCallback",
			Handler:    _Video_TranscodeCallback_Handler,
		},
		{
			MethodName: "ListUserVideos",
			Handler:    _Video_ListUserVideos_Handler,
		},
		{
			MethodName: "SavePlayProgress",
			Handler:    _Video_SavePlayProgress_Handler,
		},
		{
			MethodName: "GetPlayProgress",
			Handler:    _Video_GetPlayProgress_Handler,
		},
		{
			MethodName: "UpdateCover",
			Handler:    _Video_UpdateCover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
