// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stream.proto

package streamclient

import (
	"context"

	"gopan/rpc/stream/stream"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPlayUrlReq     = stream.GetPlayUrlReq
	GetPlayUrlResp    = stream.GetPlayUrlResp
	IncrPlayCountReq  = stream.IncrPlayCountReq
	IncrPlayCountResp = stream.IncrPlayCountResp
	PlayStream        = stream.PlayStream

	Stream interface {
		// 获取播放地址(带防盗链签名)
		GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error)
		// 增加播放计数
		IncrPlayCount(ctx context.Context, in *IncrPlayCountReq, opts ...grpc.CallOption) (*IncrPlayCountResp, error)
	}

	defaultStream struct {
		cli zrpc.Client
	}
)

func NewStream(cli zrpc.Client) Stream {
	return &defaultStream{
		cli: cli,
	}
}

// 获取播放地址(带防盗链签名)
func (m *defaultStream) GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error) {
	client := stream.NewStreamClient(m.cli.Conn())
	return client.GetPlayUrl(ctx, in, opts...)
}

// 增加播放计数
func (m *defaultStream) IncrPlayCount(ctx context.Context, in *IncrPlayCountReq, opts ...grpc.CallOption) (*IncrPlayCountResp, error) {
	client := stream.NewStreamClient(m.cli.Conn())
	return client.IncrPlayCount(ctx, in, opts...)
}
