// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResp struct {
	Message string `json:"message"`
}

type CommentInfo struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	Content    string `json:"content"`
	LikeCount  int64  `json:"like_count"`
	ReplyCount int    `json:"reply_count"`
	ParentId   int64  `json:"parent_id"`
	CreatedAt  int64  `json:"created_at"`
}

type DanmakuMsg struct {
	Content string  `json:"content"`
	Time    float64 `json:"time"`
	Color   string  `json:"color,default=#ffffff"`
	Mode    int     `json:"mode,default=1"`
}

type GetDanmakusResp struct {
	Danmakus []DanmakuMsg `json:"danmakus"`
}

type InitUploadReq struct {
	Filename    string `json:"filename"`
	FileSize    int64  `json:"file_size"`
	TotalChunks int32  `json:"total_chunks"`
	Title       string `json:"title"`
}

type InitUploadResp struct {
	VideoId  int64  `json:"video_id"`
	UploadId string `json:"upload_id"`
}

type LikeResp struct {
	LikeCount int64 `json:"like_count"`
	Liked     bool  `json:"liked"`
}

type ListCommentsResp struct {
	Comments   []CommentInfo `json:"comments"`
	NextCursor int64         `json:"next_cursor"`
	HasMore    bool          `json:"has_more"`
}

type ListVideosReq struct {
	Cursor   int64  `json:"cursor,default=0"`
	Limit    int    `json:"limit,default=20,range=[1:50]"`
	Category string `json:"category,optional"`
	Sort     string `json:"sort,optional"`
}

type ListVideosResp struct {
	Videos     []VideoInfo `json:"videos"`
	NextCursor int64       `json:"next_cursor"`
	HasMore    bool        `json:"has_more"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type PlayStream struct {
	Resolution string `json:"resolution"`
	Url        string `json:"url"`
	Bitrate    int    `json:"bitrate"`
}

type PlayUrlReq struct {
	Resolution string `json:"resolution,optional"`
}

type PlayUrlResp struct {
	M3u8Url string       `json:"m3u8_url"`
	Streams []PlayStream `json:"streams"`
}

type PostCommentReq struct {
	Content  string `json:"content"`
	ParentId int64  `json:"parent_id,default=0"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type SearchReq struct {
	Keyword  string `form:"keyword" json:"keyword"`
	Page     int    `form:"page,default=1" json:"page,default=1"`
	Size     int    `form:"size,default=20,range=[1:50]" json:"size,default=20,range=[1:50]"`
	Category string `form:"category,optional" json:"category,optional"`
	Sort     string `form:"sort,optional" json:"sort,optional"`
}

type SearchResp struct {
	Videos []SearchVideoInfo `json:"videos"`
	Total  int64             `json:"total"`
	Page   int               `json:"page"`
	Size   int               `json:"size"`
}

type SearchVideoInfo struct {
	Id          int64   `json:"id"`
	Title       string  `json:"title"`
	CoverUrl    string  `json:"cover_url"`
	UserId      int64   `json:"user_id"`
	Username    string  `json:"username"`
	PlayCount   int64   `json:"play_count"`
	LikeCount   int64   `json:"like_count"`
	Description string  `json:"description"`
	Duration    int     `json:"duration"`
	Category    string  `json:"category"`
	CreatedAt   int64   `json:"created_at"`
	Score       float64 `json:"score"`
}

type TranscodeInfo struct {
	Resolution string `json:"resolution"`
	M3u8Url    string `json:"m3u8_url"`
	Bitrate    int    `json:"bitrate"`
}

type UpdateProfileReq struct {
	Avatar    string `json:"avatar,optional"`
	Signature string `json:"signature,optional"`
	Email     string `json:"email,optional"`
}

type UpdateVideoReq struct {
	Title       string `json:"title,optional"`
	Description string `json:"description,optional"`
	Category    string `json:"category,optional"`
}

type UploadStatusResp struct {
	VideoId        int64   `json:"video_id"`
	TotalChunks    int32   `json:"total_chunks"`
	ReceivedChunks []int32 `json:"received_chunks"`
}

type UserProfileResp struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Signature string `json:"signature"`
	CreatedAt int64  `json:"created_at"`
}

type VideoDetailResp struct {
	Video VideoInfo `json:"video"`
}

type VideoInfo struct {
	Id              int64           `json:"id"`
	Title           string          `json:"title"`
	CoverUrl        string          `json:"cover_url"`
	UserId          int64           `json:"user_id"`
	Username        string          `json:"username"`
	PlayCount       int64           `json:"play_count"`
	LikeCount       int64           `json:"like_count"`
	Duration        int             `json:"duration"`
	Status          int             `json:"status"`
	Category        string          `json:"category,optional"`
	Description     string          `json:"description,optional"`
	AiSummary       string          `json:"ai_summary,optional"`
	AiSummaryStatus int             `json:"ai_summary_status,optional"`
	CreatedAt       int64           `json:"created_at"`
	Transcodes      []TranscodeInfo `json:"transcodes,optional"`
}

	// --- 管理员相关类型 ---
	type AdminVideoInfo struct {
		Id        int64  `json:"id"`
		Title     string `json:"title"`
		CoverUrl  string `json:"cover_url"`
		UserId    int64  `json:"user_id"`
		Username  string `json:"username"`
		Status    int    `json:"status"`
		PlayCount int64  `json:"play_count"`
		CreatedAt int64  `json:"created_at"`
	}

	type AdminListVideosResp struct {
		Videos     []AdminVideoInfo `json:"videos"`
		NextCursor int64            `json:"next_cursor"`
		HasMore    bool             `json:"has_more"`
	}

type AIAnalyzeReq struct {
	VideoId int64 `json:"video_id"`
}

type AIAnalyzeResp struct {
	Status  int    `json:"status"`  // 0:未生成 1:生成中 2:已完成 3:失败
	Summary string `json:"summary"` // status=2 时有内容
}
	