// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: rpc/search/search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Search_SearchVideos_FullMethodName = "/search.Search/SearchVideos"
	Search_IndexVideo_FullMethodName   = "/search.Search/IndexVideo"
	Search_RemoveVideo_FullMethodName  = "/search.Search/RemoveVideo"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 搜索服务
type SearchClient interface {
	// 搜索视频
	SearchVideos(ctx context.Context, in *SearchVideosReq, opts ...grpc.CallOption) (*SearchVideosResp, error)
	// 索引视频(创建/更新)
	IndexVideo(ctx context.Context, in *IndexVideoReq, opts ...grpc.CallOption) (*IndexVideoResp, error)
	// 从索引中移除
	RemoveVideo(ctx context.Context, in *RemoveVideoReq, opts ...grpc.CallOption) (*RemoveVideoResp, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) SearchVideos(ctx context.Context, in *SearchVideosReq, opts ...grpc.CallOption) (*SearchVideosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVideosResp)
	err := c.cc.Invoke(ctx, Search_SearchVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) IndexVideo(ctx context.Context, in *IndexVideoReq, opts ...grpc.CallOption) (*IndexVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexVideoResp)
	err := c.cc.Invoke(ctx, Search_IndexVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) RemoveVideo(ctx context.Context, in *RemoveVideoReq, opts ...grpc.CallOption) (*RemoveVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVideoResp)
	err := c.cc.Invoke(ctx, Search_RemoveVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility.
//
// 搜索服务
type SearchServer interface {
	// 搜索视频
	SearchVideos(context.Context, *SearchVideosReq) (*SearchVideosResp, error)
	// 索引视频(创建/更新)
	IndexVideo(context.Context, *IndexVideoReq) (*IndexVideoResp, error)
	// 从索引中移除
	RemoveVideo(context.Context, *RemoveVideoReq) (*RemoveVideoResp, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServer struct{}

func (UnimplementedSearchServer) SearchVideos(context.Context, *SearchVideosReq) (*SearchVideosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVideos not implemented")
}
func (UnimplementedSearchServer) IndexVideo(context.Context, *IndexVideoReq) (*IndexVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexVideo not implemented")
}
func (UnimplementedSearchServer) RemoveVideo(context.Context, *RemoveVideoReq) (*RemoveVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVideo not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}
func (UnimplementedSearchServer) testEmbeddedByValue()                {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	// If the following call panics, it indicates UnimplementedSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_SearchVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchVideos(ctx, req.(*SearchVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_IndexVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).IndexVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_IndexVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).IndexVideo(ctx, req.(*IndexVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_RemoveVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).RemoveVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_RemoveVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).RemoveVideo(ctx, req.(*RemoveVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchVideos",
			Handler:    _Search_SearchVideos_Handler,
		},
		{
			MethodName: "IndexVideo",
			Handler:    _Search_IndexVideo_Handler,
		},
		{
			MethodName: "RemoveVideo",
			Handler:    _Search_RemoveVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/search/search.proto",
}
