// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchVideosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // 分类过滤
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`         // relevance/newest/hot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosReq) Reset() {
	*x = SearchVideosReq{}
	mi := &file_rpc_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosReq) ProtoMessage() {}

func (x *SearchVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosReq.ProtoReflect.Descriptor instead.
func (*SearchVideosReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchVideosReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchVideosReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchVideosReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchVideosReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type SearchVideosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*SearchVideoInfo     `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosResp) Reset() {
	*x = SearchVideosResp{}
	mi := &file_rpc_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosResp) ProtoMessage() {}

func (x *SearchVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosResp.ProtoReflect.Descriptor instead.
func (*SearchVideosResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchVideosResp) GetVideos() []*SearchVideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchVideosResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchVideosResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchVideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	PlayCount     int64                  `protobuf:"varint,6,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int32                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`
	Category      string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Score         float64                `protobuf:"fixed64,12,opt,name=score,proto3" json:"score,omitempty"` // 相关性得分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoInfo) Reset() {
	*x = SearchVideoInfo{}
	mi := &file_rpc_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoInfo) ProtoMessage() {}

func (x *SearchVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoInfo.ProtoReflect.Descriptor instead.
func (*SearchVideoInfo) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVideoInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchVideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchVideoInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchVideoInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchVideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *SearchVideoInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *SearchVideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchVideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SearchVideoInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchVideoInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SearchVideoInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type IndexVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	PlayCount     int64                  `protobuf:"varint,8,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Duration      int32                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexVideoReq) Reset() {
	*x = IndexVideoReq{}
	mi := &file_rpc_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexVideoReq) ProtoMessage() {}

func (x *IndexVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexVideoReq.ProtoReflect.Descriptor instead.
func (*IndexVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *IndexVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *IndexVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IndexVideoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IndexVideoReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IndexVideoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IndexVideoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IndexVideoReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *IndexVideoReq) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *IndexVideoReq) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *IndexVideoReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type IndexVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexVideoResp) Reset() {
	*x = IndexVideoResp{}
	mi := &file_rpc_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexVideoResp) ProtoMessage() {}

func (x *IndexVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexVideoResp.ProtoReflect.Descriptor instead.
func (*IndexVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{4}
}

type RemoveVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoReq) Reset() {
	*x = RemoveVideoReq{}
	mi := &file_rpc_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoReq) ProtoMessage() {}

func (x *RemoveVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoReq.ProtoReflect.Descriptor instead.
func (*RemoveVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type RemoveVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoResp) Reset() {
	*x = RemoveVideoResp{}
	mi := &file_rpc_search_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoResp) ProtoMessage() {}

func (x *RemoveVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoResp.ProtoReflect.Descriptor instead.
func (*RemoveVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{6}
}

var File_rpc_search_search_proto protoreflect.FileDescriptor

const file_rpc_search_search_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/search/search.proto\x12\x06search\"\x83\x01\n" +
	"\x0fSearchVideosReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\"\x81\x01\n" +
	"\x10SearchVideosResp\x12/\n" +
	"\x06videos\x18\x01 \x03(\v2\x17.search.SearchVideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\xd6\x02\n" +
	"\x0fSearchVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"play_count\x18\x06 \x01(\x03R\tplayCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\t \x01(\x05R\bduration\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05score\x18\f \x01(\x01R\x05score\"\xaa\x02\n" +
	"\rIndexVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x1d\n" +
	"\n" +
	"play_count\x18\b \x01(\x03R\tplayCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\"\x10\n" +
	"\x0eIndexVideoResp\"+\n" +
	"\x0eRemoveVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"\x11\n" +
	"\x0fRemoveVideoResp2\xc8\x01\n" +
	"\x06Search\x12A\n" +
	"\fSearchVideos\x12\x17.search.SearchVideosReq\x1a\x18.search.SearchVideosResp\x12;\n" +
	"\n" +
	"IndexVideo\x12\x15.search.IndexVideoReq\x1a\x16.search.IndexVideoResp\x12>\n" +
	"\vRemoveVideo\x12\x16.search.RemoveVideoReq\x1a\x17.search.RemoveVideoRespB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_rpc_search_search_proto_rawDescOnce sync.Once
	file_rpc_search_search_proto_rawDescData []byte
)

func file_rpc_search_search_proto_rawDescGZIP() []byte {
	file_rpc_search_search_proto_rawDescOnce.Do(func() {
		file_rpc_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_search_search_proto_rawDesc), len(file_rpc_search_search_proto_rawDesc)))
	})
	return file_rpc_search_search_proto_rawDescData
}

var file_rpc_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_search_search_proto_goTypes = []any{
	(*SearchVideosReq)(nil),  // 0: search.SearchVideosReq
	(*SearchVideosResp)(nil), // 1: search.SearchVideosResp
	(*SearchVideoInfo)(nil),  // 2: search.SearchVideoInfo
	(*IndexVideoReq)(nil),    // 3: search.IndexVideoReq
	(*IndexVideoResp)(nil),   // 4: search.IndexVideoResp
	(*RemoveVideoReq)(nil),   // 5: search.RemoveVideoReq
	(*RemoveVideoResp)(nil),  // 6: search.RemoveVideoResp
}
var file_rpc_search_search_proto_depIdxs = []int32{
	2, // 0: search.SearchVideosResp.videos:type_name -> search.SearchVideoInfo
	0, // 1: search.Search.SearchVideos:input_type -> search.SearchVideosReq
	3, // 2: search.Search.IndexVideo:input_type -> search.IndexVideoReq
	5, // 3: search.Search.RemoveVideo:input_type -> search.RemoveVideoReq
	1, // 4: search.Search.SearchVideos:output_type -> search.SearchVideosResp
	4, // 5: search.Search.IndexVideo:output_type -> search.IndexVideoResp
	6, // 6: search.Search.RemoveVideo:output_type -> search.RemoveVideoResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_search_search_proto_init() }
func file_rpc_search_search_proto_init() {
	if File_rpc_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_search_search_proto_rawDesc), len(file_rpc_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_search_search_proto_goTypes,
		DependencyIndexes: file_rpc_search_search_proto_depIdxs,
		MessageInfos:      file_rpc_search_search_proto_msgTypes,
	}.Build()
	File_rpc_search_search_proto = out.File
	file_rpc_search_search_proto_goTypes = nil
	file_rpc_search_search_proto_depIdxs = nil
}
