// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/transcode/transcode.proto

package transcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // 源文件在对象存储的key
	Resolutions   []string               `protobuf:"bytes,3,rep,name=resolutions,proto3" json:"resolutions,omitempty"`              // 目标分辨率: 360p/480p/720p/1080p
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskReq) Reset() {
	*x = SubmitTaskReq{}
	mi := &file_rpc_transcode_transcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskReq) ProtoMessage() {}

func (x *SubmitTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transcode_transcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskReq.ProtoReflect.Descriptor instead.
func (*SubmitTaskReq) Descriptor() ([]byte, []int) {
	return file_rpc_transcode_transcode_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SubmitTaskReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *SubmitTaskReq) GetResolutions() []string {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type SubmitTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResp) Reset() {
	*x = SubmitTaskResp{}
	mi := &file_rpc_transcode_transcode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResp) ProtoMessage() {}

func (x *SubmitTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transcode_transcode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResp.ProtoReflect.Descriptor instead.
func (*SubmitTaskResp) Descriptor() ([]byte, []int) {
	return file_rpc_transcode_transcode_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type QueryTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskReq) Reset() {
	*x = QueryTaskReq{}
	mi := &file_rpc_transcode_transcode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskReq) ProtoMessage() {}

func (x *QueryTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transcode_transcode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskReq.ProtoReflect.Descriptor instead.
func (*QueryTaskReq) Descriptor() ([]byte, []int) {
	return file_rpc_transcode_transcode_proto_rawDescGZIP(), []int{2}
}

func (x *QueryTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *QueryTaskReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type QueryTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0:排队 1:转码中 2:成功 3:失败
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Results       []*TranscodeResult     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskResp) Reset() {
	*x = QueryTaskResp{}
	mi := &file_rpc_transcode_transcode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskResp) ProtoMessage() {}

func (x *QueryTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transcode_transcode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskResp.ProtoReflect.Descriptor instead.
func (*QueryTaskResp) Descriptor() ([]byte, []int) {
	return file_rpc_transcode_transcode_proto_rawDescGZIP(), []int{3}
}

func (x *QueryTaskResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryTaskResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *QueryTaskResp) GetResults() []*TranscodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TranscodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	M3U8Url       string                 `protobuf:"bytes,2,opt,name=m3u8_url,json=m3u8Url,proto3" json:"m3u8_url,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeResult) Reset() {
	*x = TranscodeResult{}
	mi := &file_rpc_transcode_transcode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResult) ProtoMessage() {}

func (x *TranscodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transcode_transcode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResult.ProtoReflect.Descriptor instead.
func (*TranscodeResult) Descriptor() ([]byte, []int) {
	return file_rpc_transcode_transcode_proto_rawDescGZIP(), []int{4}
}

func (x *TranscodeResult) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *TranscodeResult) GetM3U8Url() string {
	if x != nil {
		return x.M3U8Url
	}
	return ""
}

func (x *TranscodeResult) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *TranscodeResult) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *TranscodeResult) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_rpc_transcode_transcode_proto protoreflect.FileDescriptor

const file_rpc_transcode_transcode_proto_rawDesc = "" +
	"\n" +
	"\x1drpc/transcode/transcode.proto\x12\ttranscode\"k\n" +
	"\rSubmitTaskReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12 \n" +
	"\vresolutions\x18\x03 \x03(\tR\vresolutions\")\n" +
	"\x0eSubmitTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"B\n" +
	"\fQueryTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"z\n" +
	"\rQueryTaskResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x124\n" +
	"\aresults\x18\x03 \x03(\v2\x1a.transcode.TranscodeResultR\aresults\"\x9f\x01\n" +
	"\x0fTranscodeResult\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\x12\x19\n" +
	"\bm3u8_url\x18\x02 \x01(\tR\am3u8Url\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration2\x8e\x01\n" +
	"\tTranscode\x12A\n" +
	"\n" +
	"SubmitTask\x12\x18.transcode.SubmitTaskReq\x1a\x19.transcode.SubmitTaskResp\x12>\n" +
	"\tQueryTask\x12\x17.transcode.QueryTaskReq\x1a\x18.transcode.QueryTaskRespB\rZ\v./transcodeb\x06proto3"

var (
	file_rpc_transcode_transcode_proto_rawDescOnce sync.Once
	file_rpc_transcode_transcode_proto_rawDescData []byte
)

func file_rpc_transcode_transcode_proto_rawDescGZIP() []byte {
	file_rpc_transcode_transcode_proto_rawDescOnce.Do(func() {
		file_rpc_transcode_transcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_transcode_transcode_proto_rawDesc), len(file_rpc_transcode_transcode_proto_rawDesc)))
	})
	return file_rpc_transcode_transcode_proto_rawDescData
}

var file_rpc_transcode_transcode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_transcode_transcode_proto_goTypes = []any{
	(*SubmitTaskReq)(nil),   // 0: transcode.SubmitTaskReq
	(*SubmitTaskResp)(nil),  // 1: transcode.SubmitTaskResp
	(*QueryTaskReq)(nil),    // 2: transcode.QueryTaskReq
	(*QueryTaskResp)(nil),   // 3: transcode.QueryTaskResp
	(*TranscodeResult)(nil), // 4: transcode.TranscodeResult
}
var file_rpc_transcode_transcode_proto_depIdxs = []int32{
	4, // 0: transcode.QueryTaskResp.results:type_name -> transcode.TranscodeResult
	0, // 1: transcode.Transcode.SubmitTask:input_type -> transcode.SubmitTaskReq
	2, // 2: transcode.Transcode.QueryTask:input_type -> transcode.QueryTaskReq
	1, // 3: transcode.Transcode.SubmitTask:output_type -> transcode.SubmitTaskResp
	3, // 4: transcode.Transcode.QueryTask:output_type -> transcode.QueryTaskResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_transcode_transcode_proto_init() }
func file_rpc_transcode_transcode_proto_init() {
	if File_rpc_transcode_transcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_transcode_transcode_proto_rawDesc), len(file_rpc_transcode_transcode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_transcode_transcode_proto_goTypes,
		DependencyIndexes: file_rpc_transcode_transcode_proto_depIdxs,
		MessageInfos:      file_rpc_transcode_transcode_proto_msgTypes,
	}.Build()
	File_rpc_transcode_transcode_proto = out.File
	file_rpc_transcode_transcode_proto_goTypes = nil
	file_rpc_transcode_transcode_proto_depIdxs = nil
}
