// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/interact/interact.proto

package interact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{0}
}

func (x *LikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type LikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResp) Reset() {
	*x = LikeResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResp) ProtoMessage() {}

func (x *LikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResp.ProtoReflect.Descriptor instead.
func (*LikeResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type UnlikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReq) Reset() {
	*x = UnlikeReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReq) ProtoMessage() {}

func (x *UnlikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReq.ProtoReflect.Descriptor instead.
func (*UnlikeReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnlikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeResp) Reset() {
	*x = UnlikeResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeResp) ProtoMessage() {}

func (x *UnlikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeResp.ProtoReflect.Descriptor instead.
func (*UnlikeResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type GetLikeStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusReq) Reset() {
	*x = GetLikeStatusReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusReq) ProtoMessage() {}

func (x *GetLikeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusReq.ProtoReflect.Descriptor instead.
func (*GetLikeStatusReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{4}
}

func (x *GetLikeStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLikeStatusReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetLikeStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusResp) Reset() {
	*x = GetLikeStatusResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusResp) ProtoMessage() {}

func (x *GetLikeStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusResp.ProtoReflect.Descriptor instead.
func (*GetLikeStatusResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{5}
}

func (x *GetLikeStatusResp) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *GetLikeStatusResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type FavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteReq) Reset() {
	*x = FavoriteReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteReq) ProtoMessage() {}

func (x *FavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteReq.ProtoReflect.Descriptor instead.
func (*FavoriteReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{6}
}

func (x *FavoriteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type FavoriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteResp) Reset() {
	*x = FavoriteResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteResp) ProtoMessage() {}

func (x *FavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteResp.ProtoReflect.Descriptor instead.
func (*FavoriteResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{7}
}

type UnfavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteReq) Reset() {
	*x = UnfavoriteReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteReq) ProtoMessage() {}

func (x *UnfavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteReq.ProtoReflect.Descriptor instead.
func (*UnfavoriteReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{8}
}

func (x *UnfavoriteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfavoriteReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnfavoriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteResp) Reset() {
	*x = UnfavoriteResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteResp) ProtoMessage() {}

func (x *UnfavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteResp.ProtoReflect.Descriptor instead.
func (*UnfavoriteResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{9}
}

type GetFavoriteStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteStatusReq) Reset() {
	*x = GetFavoriteStatusReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteStatusReq) ProtoMessage() {}

func (x *GetFavoriteStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteStatusReq.ProtoReflect.Descriptor instead.
func (*GetFavoriteStatusReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{10}
}

func (x *GetFavoriteStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFavoriteStatusReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetFavoriteStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorited     bool                   `protobuf:"varint,1,opt,name=favorited,proto3" json:"favorited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteStatusResp) Reset() {
	*x = GetFavoriteStatusResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteStatusResp) ProtoMessage() {}

func (x *GetFavoriteStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteStatusResp.ProtoReflect.Descriptor instead.
func (*GetFavoriteStatusResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{11}
}

func (x *GetFavoriteStatusResp) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

type PostCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 回复的评论ID(0表示顶级评论)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReq) Reset() {
	*x = PostCommentReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReq) ProtoMessage() {}

func (x *PostCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReq.ProtoReflect.Descriptor instead.
func (*PostCommentReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{12}
}

func (x *PostCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostCommentReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *PostCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type PostCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentResp) Reset() {
	*x = PostCommentResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentResp) ProtoMessage() {}

func (x *PostCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentResp.ProtoReflect.Descriptor instead.
func (*PostCommentResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{13}
}

func (x *PostCommentResp) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type ListCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"` // hot/newest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReq) Reset() {
	*x = ListCommentsReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReq) ProtoMessage() {}

func (x *ListCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReq.ProtoReflect.Descriptor instead.
func (*ListCommentsReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{14}
}

func (x *ListCommentsReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ListCommentsReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListCommentsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommentsReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResp) Reset() {
	*x = ListCommentsResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResp) ProtoMessage() {}

func (x *ListCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResp.ProtoReflect.Descriptor instead.
func (*ListCommentsResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{15}
}

func (x *ListCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ListCommentsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     int64                  `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,7,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	ParentId      int64                  `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_rpc_interact_interact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{16}
}

func (x *CommentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *CommentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{18}
}

type SendDanmakuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Time          float64                `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"` // 弹幕出现时间(秒)
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"` // 颜色
	Mode          int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`  // 弹幕模式: 1:滚动 2:顶部 3:底部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDanmakuReq) Reset() {
	*x = SendDanmakuReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDanmakuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDanmakuReq) ProtoMessage() {}

func (x *SendDanmakuReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDanmakuReq.ProtoReflect.Descriptor instead.
func (*SendDanmakuReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{19}
}

func (x *SendDanmakuReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendDanmakuReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SendDanmakuReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendDanmakuReq) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SendDanmakuReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SendDanmakuReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type SendDanmakuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DanmakuId     int64                  `protobuf:"varint,1,opt,name=danmaku_id,json=danmakuId,proto3" json:"danmaku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDanmakuResp) Reset() {
	*x = SendDanmakuResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDanmakuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDanmakuResp) ProtoMessage() {}

func (x *SendDanmakuResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDanmakuResp.ProtoReflect.Descriptor instead.
func (*SendDanmakuResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{20}
}

func (x *SendDanmakuResp) GetDanmakuId() int64 {
	if x != nil {
		return x.DanmakuId
	}
	return 0
}

type GetDanmakusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Time          float64                `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"` // 获取该时间点附近的弹幕
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDanmakusReq) Reset() {
	*x = GetDanmakusReq{}
	mi := &file_rpc_interact_interact_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDanmakusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDanmakusReq) ProtoMessage() {}

func (x *GetDanmakusReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDanmakusReq.ProtoReflect.Descriptor instead.
func (*GetDanmakusReq) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{21}
}

func (x *GetDanmakusReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetDanmakusReq) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type GetDanmakusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Danmakus      []*DanmakuInfo         `protobuf:"bytes,1,rep,name=danmakus,proto3" json:"danmakus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDanmakusResp) Reset() {
	*x = GetDanmakusResp{}
	mi := &file_rpc_interact_interact_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDanmakusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDanmakusResp) ProtoMessage() {}

func (x *GetDanmakusResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDanmakusResp.ProtoReflect.Descriptor instead.
func (*GetDanmakusResp) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{22}
}

func (x *GetDanmakusResp) GetDanmakus() []*DanmakuInfo {
	if x != nil {
		return x.Danmakus
	}
	return nil
}

type DanmakuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Time          float64                `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Mode          int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuInfo) Reset() {
	*x = DanmakuInfo{}
	mi := &file_rpc_interact_interact_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuInfo) ProtoMessage() {}

func (x *DanmakuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_interact_interact_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuInfo.ProtoReflect.Descriptor instead.
func (*DanmakuInfo) Descriptor() ([]byte, []int) {
	return file_rpc_interact_interact_proto_rawDescGZIP(), []int{23}
}

func (x *DanmakuInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DanmakuInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DanmakuInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmakuInfo) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *DanmakuInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *DanmakuInfo) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

var File_rpc_interact_interact_proto protoreflect.FileDescriptor

const file_rpc_interact_interact_proto_rawDesc = "" +
	"\n" +
	"\x1brpc/interact/interact.proto\x12\binteract\"=\n" +
	"\aLikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\")\n" +
	"\bLikeResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\"?\n" +
	"\tUnlikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"+\n" +
	"\n" +
	"UnlikeResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\"F\n" +
	"\x10GetLikeStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"H\n" +
	"\x11GetLikeStatusResp\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"A\n" +
	"\vFavoriteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x0e\n" +
	"\fFavoriteResp\"C\n" +
	"\rUnfavoriteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x10\n" +
	"\x0eUnfavoriteResp\"J\n" +
	"\x14GetFavoriteStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"5\n" +
	"\x15GetFavoriteStatusResp\x12\x1c\n" +
	"\tfavorited\x18\x01 \x01(\bR\tfavorited\"{\n" +
	"\x0ePostCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\"0\n" +
	"\x0fPostCommentResp\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\"n\n" +
	"\x0fListCommentsReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"\x81\x01\n" +
	"\x10ListCommentsResp\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x15.interact.CommentInfoR\bcomments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x80\x02\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\a \x01(\x05R\n" +
	"replyCount\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"J\n" +
	"\x10DeleteCommentReq\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x13\n" +
	"\x11DeleteCommentResp\"\x9c\x01\n" +
	"\x0eSendDanmakuReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x01R\x04time\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode\"0\n" +
	"\x0fSendDanmakuResp\x12\x1d\n" +
	"\n" +
	"danmaku_id\x18\x01 \x01(\x03R\tdanmakuId\"?\n" +
	"\x0eGetDanmakusReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x01R\x04time\"D\n" +
	"\x0fGetDanmakusResp\x121\n" +
	"\bdanmakus\x18\x01 \x03(\v2\x15.interact.DanmakuInfoR\bdanmakus\"\x8e\x01\n" +
	"\vDanmakuInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x01R\x04time\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode2\xe7\x05\n" +
	"\bInteract\x12-\n" +
	"\x04Like\x12\x11.interact.LikeReq\x1a\x12.interact.LikeResp\x123\n" +
	"\x06Unlike\x12\x13.interact.UnlikeReq\x1a\x14.interact.UnlikeResp\x12H\n" +
	"\rGetLikeStatus\x12\x1a.interact.GetLikeStatusReq\x1a\x1b.interact.GetLikeStatusResp\x129\n" +
	"\bFavorite\x12\x15.interact.FavoriteReq\x1a\x16.interact.FavoriteResp\x12?\n" +
	"\n" +
	"Unfavorite\x12\x17.interact.UnfavoriteReq\x1a\x18.interact.UnfavoriteResp\x12T\n" +
	"\x11GetFavoriteStatus\x12\x1e.interact.GetFavoriteStatusReq\x1a\x1f.interact.GetFavoriteStatusResp\x12B\n" +
	"\vPostComment\x12\x18.interact.PostCommentReq\x1a\x19.interact.PostCommentResp\x12E\n" +
	"\fListComments\x12\x19.interact.ListCommentsReq\x1a\x1a.interact.ListCommentsResp\x12H\n" +
	"\rDeleteComment\x12\x1a.interact.DeleteCommentReq\x1a\x1b.interact.DeleteCommentResp\x12B\n" +
	"\vSendDanmaku\x12\x18.interact.SendDanmakuReq\x1a\x19.interact.SendDanmakuResp\x12B\n" +
	"\vGetDanmakus\x12\x18.interact.GetDanmakusReq\x1a\x19.interact.GetDanmakusRespB\fZ\n" +
	"./interactb\x06proto3"

var (
	file_rpc_interact_interact_proto_rawDescOnce sync.Once
	file_rpc_interact_interact_proto_rawDescData []byte
)

func file_rpc_interact_interact_proto_rawDescGZIP() []byte {
	file_rpc_interact_interact_proto_rawDescOnce.Do(func() {
		file_rpc_interact_interact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_interact_interact_proto_rawDesc), len(file_rpc_interact_interact_proto_rawDesc)))
	})
	return file_rpc_interact_interact_proto_rawDescData
}

var file_rpc_interact_interact_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_rpc_interact_interact_proto_goTypes = []any{
	(*LikeReq)(nil),               // 0: interact.LikeReq
	(*LikeResp)(nil),              // 1: interact.LikeResp
	(*UnlikeReq)(nil),             // 2: interact.UnlikeReq
	(*UnlikeResp)(nil),            // 3: interact.UnlikeResp
	(*GetLikeStatusReq)(nil),      // 4: interact.GetLikeStatusReq
	(*GetLikeStatusResp)(nil),     // 5: interact.GetLikeStatusResp
	(*FavoriteReq)(nil),           // 6: interact.FavoriteReq
	(*FavoriteResp)(nil),          // 7: interact.FavoriteResp
	(*UnfavoriteReq)(nil),         // 8: interact.UnfavoriteReq
	(*UnfavoriteResp)(nil),        // 9: interact.UnfavoriteResp
	(*GetFavoriteStatusReq)(nil),  // 10: interact.GetFavoriteStatusReq
	(*GetFavoriteStatusResp)(nil), // 11: interact.GetFavoriteStatusResp
	(*PostCommentReq)(nil),        // 12: interact.PostCommentReq
	(*PostCommentResp)(nil),       // 13: interact.PostCommentResp
	(*ListCommentsReq)(nil),       // 14: interact.ListCommentsReq
	(*ListCommentsResp)(nil),      // 15: interact.ListCommentsResp
	(*CommentInfo)(nil),           // 16: interact.CommentInfo
	(*DeleteCommentReq)(nil),      // 17: interact.DeleteCommentReq
	(*DeleteCommentResp)(nil),     // 18: interact.DeleteCommentResp
	(*SendDanmakuReq)(nil),        // 19: interact.SendDanmakuReq
	(*SendDanmakuResp)(nil),       // 20: interact.SendDanmakuResp
	(*GetDanmakusReq)(nil),        // 21: interact.GetDanmakusReq
	(*GetDanmakusResp)(nil),       // 22: interact.GetDanmakusResp
	(*DanmakuInfo)(nil),           // 23: interact.DanmakuInfo
}
var file_rpc_interact_interact_proto_depIdxs = []int32{
	16, // 0: interact.ListCommentsResp.comments:type_name -> interact.CommentInfo
	23, // 1: interact.GetDanmakusResp.danmakus:type_name -> interact.DanmakuInfo
	0,  // 2: interact.Interact.Like:input_type -> interact.LikeReq
	2,  // 3: interact.Interact.Unlike:input_type -> interact.UnlikeReq
	4,  // 4: interact.Interact.GetLikeStatus:input_type -> interact.GetLikeStatusReq
	6,  // 5: interact.Interact.Favorite:input_type -> interact.FavoriteReq
	8,  // 6: interact.Interact.Unfavorite:input_type -> interact.UnfavoriteReq
	10, // 7: interact.Interact.GetFavoriteStatus:input_type -> interact.GetFavoriteStatusReq
	12, // 8: interact.Interact.PostComment:input_type -> interact.PostCommentReq
	14, // 9: interact.Interact.ListComments:input_type -> interact.ListCommentsReq
	17, // 10: interact.Interact.DeleteComment:input_type -> interact.DeleteCommentReq
	19, // 11: interact.Interact.SendDanmaku:input_type -> interact.SendDanmakuReq
	21, // 12: interact.Interact.GetDanmakus:input_type -> interact.GetDanmakusReq
	1,  // 13: interact.Interact.Like:output_type -> interact.LikeResp
	3,  // 14: interact.Interact.Unlike:output_type -> interact.UnlikeResp
	5,  // 15: interact.Interact.GetLikeStatus:output_type -> interact.GetLikeStatusResp
	7,  // 16: interact.Interact.Favorite:output_type -> interact.FavoriteResp
	9,  // 17: interact.Interact.Unfavorite:output_type -> interact.UnfavoriteResp
	11, // 18: interact.Interact.GetFavoriteStatus:output_type -> interact.GetFavoriteStatusResp
	13, // 19: interact.Interact.PostComment:output_type -> interact.PostCommentResp
	15, // 20: interact.Interact.ListComments:output_type -> interact.ListCommentsResp
	18, // 21: interact.Interact.DeleteComment:output_type -> interact.DeleteCommentResp
	20, // 22: interact.Interact.SendDanmaku:output_type -> interact.SendDanmakuResp
	22, // 23: interact.Interact.GetDanmakus:output_type -> interact.GetDanmakusResp
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_interact_interact_proto_init() }
func file_rpc_interact_interact_proto_init() {
	if File_rpc_interact_interact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_interact_interact_proto_rawDesc), len(file_rpc_interact_interact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_interact_interact_proto_goTypes,
		DependencyIndexes: file_rpc_interact_interact_proto_depIdxs,
		MessageInfos:      file_rpc_interact_interact_proto_msgTypes,
	}.Build()
	File_rpc_interact_interact_proto = out.File
	file_rpc_interact_interact_proto_goTypes = nil
	file_rpc_interact_interact_proto_depIdxs = nil
}
