// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package videoclient

import (
	"context"

	"gopan/rpc/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteVideoReq        = video.DeleteVideoReq
	DeleteVideoResp       = video.DeleteVideoResp
	GetPlayProgressReq    = video.GetPlayProgressReq
	GetPlayProgressResp   = video.GetPlayProgressResp
	GetVideoReq           = video.GetVideoReq
	GetVideoResp          = video.GetVideoResp
	InitUploadReq         = video.InitUploadReq
	InitUploadResp        = video.InitUploadResp
	ListUserVideosReq     = video.ListUserVideosReq
	ListVideosReq         = video.ListVideosReq
	ListVideosResp        = video.ListVideosResp
	MergeChunksReq        = video.MergeChunksReq
	MergeChunksResp       = video.MergeChunksResp
	SavePlayProgressReq   = video.SavePlayProgressReq
	SavePlayProgressResp  = video.SavePlayProgressResp
	TranscodeCallbackReq  = video.TranscodeCallbackReq
	TranscodeCallbackResp = video.TranscodeCallbackResp
	TranscodeInfo         = video.TranscodeInfo
	UpdateVideoReq        = video.UpdateVideoReq
	UpdateVideoResp       = video.UpdateVideoResp
	UploadChunkReq        = video.UploadChunkReq
	UploadChunkResp       = video.UploadChunkResp
	UploadStatusReq       = video.UploadStatusReq
	UploadStatusResp      = video.UploadStatusResp
	VideoInfo             = video.VideoInfo

	Video interface {
		// 初始化上传（返回 upload_id，创建视频记录）
		InitUpload(ctx context.Context, in *InitUploadReq, opts ...grpc.CallOption) (*InitUploadResp, error)
		// 上传单个分片（非 stream，每个 chunk 独立 RPC）
		UploadChunk(ctx context.Context, in *UploadChunkReq, opts ...grpc.CallOption) (*UploadChunkResp, error)
		// 查询上传进度（已收到的 chunk 列表）
		UploadStatus(ctx context.Context, in *UploadStatusReq, opts ...grpc.CallOption) (*UploadStatusResp, error)
		// 合并分片（合并前校验完整性）
		MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error)
		// 获取视频列表
		ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
		// 获取视频详情
		GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error)
		// 更新视频信息
		UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error)
		// 删除视频
		DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
		// 转码完成回调
		TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error)
		// 获取用户视频列表
		ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
		// 保存播放进度
		SavePlayProgress(ctx context.Context, in *SavePlayProgressReq, opts ...grpc.CallOption) (*SavePlayProgressResp, error)
		// 获取播放进度
		GetPlayProgress(ctx context.Context, in *GetPlayProgressReq, opts ...grpc.CallOption) (*GetPlayProgressResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 初始化上传（返回 upload_id，创建视频记录）
func (m *defaultVideo) InitUpload(ctx context.Context, in *InitUploadReq, opts ...grpc.CallOption) (*InitUploadResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.InitUpload(ctx, in, opts...)
}

// 上传单个分片（非 stream，每个 chunk 独立 RPC）
func (m *defaultVideo) UploadChunk(ctx context.Context, in *UploadChunkReq, opts ...grpc.CallOption) (*UploadChunkResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UploadChunk(ctx, in, opts...)
}

// 查询上传进度（已收到的 chunk 列表）
func (m *defaultVideo) UploadStatus(ctx context.Context, in *UploadStatusReq, opts ...grpc.CallOption) (*UploadStatusResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UploadStatus(ctx, in, opts...)
}

// 合并分片（合并前校验完整性）
func (m *defaultVideo) MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.MergeChunks(ctx, in, opts...)
}

// 获取视频列表
func (m *defaultVideo) ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.ListVideos(ctx, in, opts...)
}

// 获取视频详情
func (m *defaultVideo) GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

// 更新视频信息
func (m *defaultVideo) UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UpdateVideo(ctx, in, opts...)
}

// 删除视频
func (m *defaultVideo) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

// 转码完成回调
func (m *defaultVideo) TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.TranscodeCallback(ctx, in, opts...)
}

// 获取用户视频列表
func (m *defaultVideo) ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.ListUserVideos(ctx, in, opts...)
}

// 保存播放进度
func (m *defaultVideo) SavePlayProgress(ctx context.Context, in *SavePlayProgressReq, opts ...grpc.CallOption) (*SavePlayProgressResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.SavePlayProgress(ctx, in, opts...)
}

// 获取播放进度
func (m *defaultVideo) GetPlayProgress(ctx context.Context, in *GetPlayProgressReq, opts ...grpc.CallOption) (*GetPlayProgressResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetPlayProgress(ctx, in, opts...)
}
