// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package videoclient

import (
	"context"

	"gopan/rpc/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteVideoReq        = video.DeleteVideoReq
	DeleteVideoResp       = video.DeleteVideoResp
	GetVideoReq           = video.GetVideoReq
	GetVideoResp          = video.GetVideoResp
	ListUserVideosReq     = video.ListUserVideosReq
	ListVideosReq         = video.ListVideosReq
	ListVideosResp        = video.ListVideosResp
	MergeChunksReq        = video.MergeChunksReq
	MergeChunksResp       = video.MergeChunksResp
	TranscodeCallbackReq  = video.TranscodeCallbackReq
	TranscodeCallbackResp = video.TranscodeCallbackResp
	TranscodeInfo         = video.TranscodeInfo
	UpdateVideoReq        = video.UpdateVideoReq
	UpdateVideoResp       = video.UpdateVideoResp
	UploadChunkReq        = video.UploadChunkReq
	UploadChunkResp       = video.UploadChunkResp
	VideoInfo             = video.VideoInfo

	Video interface {
		// 上传视频(分片)
		UploadChunk(ctx context.Context, opts ...grpc.CallOption) (video.Video_UploadChunkClient, error)
		// 合并分片
		MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error)
		// 获取视频列表
		ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
		// 获取视频详情
		GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error)
		// 更新视频信息
		UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error)
		// 删除视频
		DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
		// 转码完成回调
		TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error)
		// 获取用户视频列表
		ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 上传视频(分片)
func (m *defaultVideo) UploadChunk(ctx context.Context, opts ...grpc.CallOption) (video.Video_UploadChunkClient, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UploadChunk(ctx, opts...)
}

// 合并分片
func (m *defaultVideo) MergeChunks(ctx context.Context, in *MergeChunksReq, opts ...grpc.CallOption) (*MergeChunksResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.MergeChunks(ctx, in, opts...)
}

// 获取视频列表
func (m *defaultVideo) ListVideos(ctx context.Context, in *ListVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.ListVideos(ctx, in, opts...)
}

// 获取视频详情
func (m *defaultVideo) GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

// 更新视频信息
func (m *defaultVideo) UpdateVideo(ctx context.Context, in *UpdateVideoReq, opts ...grpc.CallOption) (*UpdateVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.UpdateVideo(ctx, in, opts...)
}

// 删除视频
func (m *defaultVideo) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

// 转码完成回调
func (m *defaultVideo) TranscodeCallback(ctx context.Context, in *TranscodeCallbackReq, opts ...grpc.CallOption) (*TranscodeCallbackResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.TranscodeCallback(ctx, in, opts...)
}

// 获取用户视频列表
func (m *defaultVideo) ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.ListUserVideos(ctx, in, opts...)
}
