// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: admin.proto

package adminclient

import (
	"context"

	"gopan/rpc/admin/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminDeleteVideoReq  = admin.AdminDeleteVideoReq
	AdminDeleteVideoResp = admin.AdminDeleteVideoResp
	AdminListVideosReq   = admin.AdminListVideosReq
	AdminListVideosResp  = admin.AdminListVideosResp
	AdminLoginReq        = admin.AdminLoginReq
	AdminLoginResp       = admin.AdminLoginResp
	AdminVideoInfo       = admin.AdminVideoInfo
	ApproveVideoReq      = admin.ApproveVideoReq
	ApproveVideoResp     = admin.ApproveVideoResp
	RejectVideoReq       = admin.RejectVideoReq
	RejectVideoResp      = admin.RejectVideoResp

	Admin interface {
		AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error)
		ListVideos(ctx context.Context, in *AdminListVideosReq, opts ...grpc.CallOption) (*AdminListVideosResp, error)
		ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*ApproveVideoResp, error)
		RejectVideo(ctx context.Context, in *RejectVideoReq, opts ...grpc.CallOption) (*RejectVideoResp, error)
		DeleteVideo(ctx context.Context, in *AdminDeleteVideoReq, opts ...grpc.CallOption) (*AdminDeleteVideoResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}

func (m *defaultAdmin) ListVideos(ctx context.Context, in *AdminListVideosReq, opts ...grpc.CallOption) (*AdminListVideosResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ListVideos(ctx, in, opts...)
}

func (m *defaultAdmin) ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*ApproveVideoResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.ApproveVideo(ctx, in, opts...)
}

func (m *defaultAdmin) RejectVideo(ctx context.Context, in *RejectVideoReq, opts ...grpc.CallOption) (*RejectVideoResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.RejectVideo(ctx, in, opts...)
}

func (m *defaultAdmin) DeleteVideo(ctx context.Context, in *AdminDeleteVideoReq, opts ...grpc.CallOption) (*AdminDeleteVideoResp, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}
